# Generated by Django 5.2.17 on 2026-08-25 14:19

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPartner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=40)),
                ("display_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country_code", models.CharField(default="ID", max_length=2)),
                ("pic_name", models.CharField(blank=True, max_length=150)),
                ("pic_title", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("pic_email", models.EmailField(blank=True, max_length=254)),
                ("pic_phone", models.CharField(blank=True, max_length=50)),
                ("npwp", models.CharField(blank=True, max_length=40)),
                ("nitku", models.CharField(blank=True, max_length=40)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_name", models.CharField(blank=True, max_length=150)),
                ("bank_account_number", models.CharField(blank=True, max_length=100)),
                ("payment_terms_days", models.PositiveIntegerField(default=0)),
                ("credit_terms_days", models.PositiveIntegerField(default=0)),
                ("credit_limit", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="business_partners",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="PartnerRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "Customer"),
                            ("VENDOR", "Vendor"),
                            ("SUBCONTRACTOR", "Subcontractor"),
                            ("MARKETPLACE_PARTNER", "Marketplace partner"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="partners.businesspartner",
                    ),
                ),
            ],
            options={
                "ordering": ("partner__code", "role_type", "-effective_from"),
            },
        ),
        migrations.AddIndex(
            model_name="businesspartner",
            index=models.Index(
                fields=["legal_entity", "is_active"], name="partners_entity_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businesspartner",
            index=models.Index(fields=["display_name"], name="partners_display_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="businesspartner",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="partners_partner_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="businesspartner",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit_limit__gte", 0)),
                name="partners_partner_credit_limit_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="businesspartner",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="partners_partner_effective_period_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="partnerrole",
            index=models.Index(
                fields=["role_type", "is_active"], name="partners_role_type_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerrole",
            constraint=models.UniqueConstraint(
                fields=("partner", "role_type", "effective_from"),
                name="partners_role_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("partner", "role_type"),
                name="partners_one_active_role_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerrole",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="partners_role_effective_period_valid",
            ),
        ),
    ]
