# Generated by Django 5.2.17 on 2026-08-26 01:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("code_normalized", models.CharField(editable=False, max_length=50)),
                ("name", models.CharField(max_length=150)),
                (
                    "accounting_treatment",
                    models.CharField(
                        choices=[
                            ("INVENTORY", "Inventory"),
                            ("ASSET", "Asset"),
                            ("EXPENSE", "Expense"),
                            ("SERVICE", "Service"),
                            ("MAKLUN", "Maklun"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inventory_classification", models.CharField(blank=True, max_length=80)),
                ("asset_class_reference", models.CharField(blank=True, max_length=80)),
                ("snapshot_production", models.BooleanField(default=False)),
                ("default_accounting_mapping_key", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_categories",
                        to="organizations.costcenter",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_categories",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "purchase categories",
                "ordering": ("legal_entity__code", "code", "-effective_from"),
                "indexes": [
                    models.Index(
                        fields=["legal_entity", "code_normalized", "is_active"],
                        name="purch_category_lookup_idx",
                    ),
                    models.Index(
                        fields=["accounting_treatment", "is_active"],
                        name="purch_category_treatment_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "code_normalized", "effective_from"),
                        name="purch_category_scope_start_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="purch_purchasecategory_effective_period_valid",
                    ),
                ],
            },
        ),
    ]
