# Generated by Django 5.2.17 on 2026-08-26 18:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_documentsequence_documentnumberallocation_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        ("projects", "0001_phase_3c"),
        ("purchasing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=120)),
                ("document_date", models.DateField()),
                ("vendor_code_snapshot", models.CharField(max_length=40)),
                ("vendor_name_snapshot", models.CharField(max_length=255)),
                ("vendor_reference", models.CharField(blank=True, max_length=120)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="IDR", max_length=3)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("tax_total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("freight_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("grand_total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("notes", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="organizations.businessunit",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order",
                        to="core.documentnumberallocation",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="projects.project",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="partners.businesspartner",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("confirm_purchaseorder", "Can confirm purchase order"),
                    ("cancel_purchaseorder", "Can cancel purchase order"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                ("item_code_snapshot", models.CharField(blank=True, max_length=64)),
                ("item_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("uom_code_snapshot", models.CharField(blank=True, max_length=20)),
                ("category_code_snapshot", models.CharField(max_length=50)),
                ("category_name_snapshot", models.CharField(max_length=150)),
                (
                    "accounting_treatment_snapshot",
                    models.CharField(
                        choices=[
                            ("INVENTORY", "Inventory"),
                            ("ASSET", "Asset"),
                            ("EXPENSE", "Expense"),
                            ("SERVICE", "Service"),
                            ("MAKLUN", "Maklun"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inventory_classification_snapshot", models.CharField(blank=True, max_length=80)),
                ("asset_class_reference_snapshot", models.CharField(blank=True, max_length=80)),
                ("snapshot_production", models.BooleanField(default=False)),
                ("accounting_mapping_key_snapshot", models.CharField(blank=True, max_length=80)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("tax_rate", models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ("line_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "line_tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("line_total", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("notes", models.TextField(blank=True)),
                (
                    "cost_center_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_line_snapshots",
                        to="organizations.costcenter",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "purchase_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="purchasing.purchasecategory",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="purchasing.purchaseorder",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["legal_entity", "state", "document_date"], name="po_list_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"), name="po_entity_document_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorderline",
            index=models.Index(
                fields=["purchase_order", "accounting_treatment_snapshot"],
                name="po_line_treatment_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.UniqueConstraint(
                fields=("purchase_order", "line_number"), name="po_line_number_unique"
            ),
        ),
    ]
