# Generated by Django 5.2.17 on 2026-08-26 19:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_documentsequence_documentnumberallocation_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        ("projects", "0001_phase_3c"),
        ("purchasing", "0002_phase_4a"),
        ("sales", "0003_phase_3c"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=120)),
                ("document_date", models.DateField()),
                (
                    "work_order_type",
                    models.CharField(
                        choices=[("INTERNAL", "Internal"), ("SUBCONTRACT", "Subcontract")],
                        max_length=16,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("VOID", "Void"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order",
                        to="core.documentnumberallocation",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="projects.project",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_orders",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="voided_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("submit_workorder", "Can submit work order"),
                    ("approve_workorder", "Can approve work order"),
                    ("void_workorder", "Can void work order"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("target_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order_outputs",
                        to="catalog.item",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outputs",
                        to="purchasing.workorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrderMaterialAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("material_code_snapshot", models.CharField(max_length=64)),
                ("material_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("planned_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "reference_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "material_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_order_material_allocations",
                        to="catalog.item",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_allocations",
                        to="purchasing.workorder",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_allocations",
                        to="purchasing.workorderoutput",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["legal_entity", "state", "document_date"], name="wo_list_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workorder",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"), name="wo_entity_doc_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderoutput",
            index=models.Index(fields=["work_order", "item"], name="wo_output_item_idx"),
        ),
        migrations.AddConstraint(
            model_name="workorderoutput",
            constraint=models.UniqueConstraint(
                fields=("work_order", "line_number"), name="wo_output_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderoutput",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_quantity__gt", 0)), name="wo_output_qty_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="workordermaterialallocation",
            index=models.Index(fields=["work_order", "output"], name="wo_material_output_idx"),
        ),
        migrations.AddConstraint(
            model_name="workordermaterialallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_quantity__gt", 0)), name="wo_material_qty_positive"
            ),
        ),
    ]
