# Generated by Django 5.2.17 on 2026-08-27 02:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_documentsequence_documentnumberallocation_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        ("purchasing", "0003_phase_4b1"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcontractMaterialDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=120)),
                ("vendor_code_snapshot", models.CharField(max_length=40)),
                ("vendor_name_snapshot", models.CharField(max_length=255)),
                ("dispatch_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_material_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_material_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_material_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.documentnumberallocation",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_dispatches",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatches",
                        to="purchasing.workorder",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("confirm_subcontractmaterialdispatch", "Can confirm material dispatch"),
                    ("cancel_subcontractmaterialdispatch", "Can cancel material dispatch"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubcontractMaterialDispatchLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                ("material_code_snapshot", models.CharField(max_length=64)),
                ("material_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "reference_cost_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatch_lines",
                        to="purchasing.workordermaterialallocation",
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="purchasing.subcontractmaterialdispatch",
                    ),
                ),
                (
                    "material_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubcontractReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=120)),
                ("vendor_code_snapshot", models.CharField(max_length=40)),
                ("vendor_name_snapshot", models.CharField(max_length=255)),
                ("receipt_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACCEPTED", "Accepted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=500)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accepted_subcontract_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_subcontract_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_subcontract_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.documentnumberallocation",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontract_receipts",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontract_receipts",
                        to="purchasing.workorder",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("accept_subcontractreceipt", "Can accept subcontract receipt"),
                    ("cancel_subcontractreceipt", "Can cancel subcontract receipt"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubcontractReceiptCostLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("JASA_SPESIFIK_VARIAN", "Jasa spesifik varian"),
                            ("JASA_UMUM", "Jasa umum"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="IDR", max_length=3)),
                ("notes", models.TextField(blank=True)),
                (
                    "output",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontract_cost_lines",
                        to="purchasing.workorderoutput",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_lines",
                        to="purchasing.subcontractreceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubcontractReceiptOutputLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("accepted_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="purchasing.workorderoutput",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="output_lines",
                        to="purchasing.subcontractreceipt",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subcontractmaterialdispatch",
            index=models.Index(
                fields=["legal_entity", "state", "dispatch_date"], name="subdisp_list_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcontractmaterialdispatch",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"), name="subdisp_entity_doc_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractmaterialdispatchline",
            index=models.Index(fields=["allocation", "dispatch"], name="subdisp_allocation_idx"),
        ),
        migrations.AddConstraint(
            model_name="subcontractmaterialdispatchline",
            constraint=models.UniqueConstraint(
                fields=("dispatch", "line_number"), name="subdisp_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcontractmaterialdispatchline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="subdisp_qty_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractreceipt",
            index=models.Index(
                fields=["legal_entity", "state", "receipt_date"], name="subrec_list_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcontractreceipt",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"), name="subrec_entity_doc_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractreceiptcostline",
            index=models.Index(fields=["receipt", "cost_type"], name="subrec_cost_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="subcontractreceiptcostline",
            constraint=models.UniqueConstraint(
                fields=("receipt", "line_number"), name="subrec_cost_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcontractreceiptcostline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="subrec_cost_nonnegative"
            ),
        ),
        migrations.AddIndex(
            model_name="subcontractreceiptoutputline",
            index=models.Index(fields=["output", "receipt"], name="subrec_output_idx"),
        ),
        migrations.AddConstraint(
            model_name="subcontractreceiptoutputline",
            constraint=models.UniqueConstraint(
                fields=("receipt", "line_number"), name="subrec_output_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcontractreceiptoutputline",
            constraint=models.CheckConstraint(
                condition=models.Q(("accepted_quantity__gt", 0)), name="subrec_qty_positive"
            ),
        ),
    ]
