# Generated by Django 5.2.17 on 2026-08-27 09:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("purchasing", "0004_phase_4b2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionRejectEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("production_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("POSTED", "Posted")],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_production_reject_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_production_reject_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_reject_entries",
                        to="purchasing.workorder",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_productionrejectentry", "Can post production reject entry"),
                    ("reverse_productionrejectline", "Can reverse production reject line"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionRejectLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("CUT", "Potong"),
                            ("SEW", "Jahit"),
                            ("QC_PACKING", "QC & Packing"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("reason", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="production.productionrejectentry",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_reject_lines",
                        to="purchasing.workorderoutput",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionRejectLineReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                ("reversed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="production.productionrejectline",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_reject_reversals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionWorkEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("production_date", models.DateField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("CUT", "Potong"),
                            ("SEW", "Jahit"),
                            ("QC_PACKING", "QC & Packing"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("POSTED", "Posted")],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_production_work_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_production_work_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_work_entries",
                        to="purchasing.workorder",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_productionworkentry", "Can post production work entry"),
                    ("reverse_productionworkline", "Can reverse production work line"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionWorkLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("sequence", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="production.productionworkentry",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_work_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_work_lines",
                        to="purchasing.workorderoutput",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionWorkLineReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                ("reversed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="production.productionworkline",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_work_reversals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="productionrejectentry",
            index=models.Index(
                fields=["legal_entity", "state", "production_date"], name="prod_reject_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionrejectline",
            index=models.Index(fields=["output", "stage"], name="prod_rej_line_outstage_idx"),
        ),
        migrations.AddConstraint(
            model_name="productionrejectline",
            constraint=models.UniqueConstraint(
                fields=("entry", "sequence"), name="prod_reject_line_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrejectline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="prod_rej_line_qty_pos"
            ),
        ),
        migrations.AddIndex(
            model_name="productionrejectlinereversal",
            index=models.Index(fields=["reversed_at"], name="prod_rej_rev_time_idx"),
        ),
        migrations.AddIndex(
            model_name="productionworkentry",
            index=models.Index(
                fields=["legal_entity", "state", "production_date"], name="prod_work_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionworkentry",
            index=models.Index(
                fields=["work_order", "stage", "state"], name="prod_work_wostage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionworkline",
            index=models.Index(fields=["output"], name="prod_work_line_output_idx"),
        ),
        migrations.AddConstraint(
            model_name="productionworkline",
            constraint=models.UniqueConstraint(
                fields=("entry", "sequence"), name="prod_work_line_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionworkline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="prod_work_line_qty_pos"
            ),
        ),
        migrations.AddIndex(
            model_name="productionworklinereversal",
            index=models.Index(fields=["reversed_at"], name="prod_work_rev_time_idx"),
        ),
    ]
