# Generated by Django 5.2.17 on 2026-08-27 11:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("production", "0001_initial"),
        ("purchasing", "0004_phase_4b2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionWarehouseHandover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("handover_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("READY_FOR_GUDANG", "Siap Gudang")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_production_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "ready_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ready_production_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_handovers",
                        to="purchasing.workorder",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("ready_productionwarehousehandover", "Can mark production handover ready"),
                    ("reverse_productionhandoverline", "Can reverse production handover line"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionWarehouseHandoverLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("sequence", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "handover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="production.productionwarehousehandover",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_handover_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_handover_lines",
                        to="purchasing.workorderoutput",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionWarehouseHandoverLineReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                ("reversed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="production.productionwarehousehandoverline",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_handover_reversals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="productionwarehousehandover",
            index=models.Index(
                fields=["legal_entity", "state", "handover_date"], name="prod_handover_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionwarehousehandover",
            index=models.Index(fields=["work_order", "state"], name="prod_handover_wo_idx"),
        ),
        migrations.AddIndex(
            model_name="productionwarehousehandoverline",
            index=models.Index(fields=["output"], name="prod_handover_line_out_idx"),
        ),
        migrations.AddConstraint(
            model_name="productionwarehousehandoverline",
            constraint=models.UniqueConstraint(
                fields=("handover", "sequence"), name="prod_handover_line_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionwarehousehandoverline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="prod_handover_line_qty_pos"
            ),
        ),
        migrations.AddIndex(
            model_name="productionwarehousehandoverlinereversal",
            index=models.Index(fields=["reversed_at"], name="prod_hand_rev_time_idx"),
        ),
    ]
