# Generated by Django 5.2.17 on 2026-08-27 11:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_employee"),
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("production", "0002_productionwarehousehandover_and_more"),
        ("purchasing", "0004_phase_4b2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productionworkentry",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.employee",
            ),
        ),
        migrations.AddField(
            model_name="productionworkentry",
            name="wage_method",
            field=models.CharField(
                choices=[("PIECE_RATE", "Borongan"), ("NO_WAGE", "Tanpa Upah")],
                default="NO_WAGE",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ProductionCostAllocationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("allocation_month", models.DateField()),
                ("rule_code", models.CharField(default="CUT_QTY_MONTHLY", max_length=32)),
                ("status", models.CharField(default="READY", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.productioncostallocationrun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionOverheadSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("source_module", models.CharField(max_length=64)),
                ("source_type", models.CharField(max_length=64)),
                ("source_document_id", models.CharField(max_length=64)),
                ("source_line_id", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("posting_date", models.DateField()),
                ("source_status", models.CharField(max_length=32)),
                ("metadata_snapshot", models.JSONField(default=dict)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionCostAllocationLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("driver_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("driver_total", models.DecimalField(decimal_places=6, max_digits=18)),
                ("ratio", models.DecimalField(decimal_places=12, max_digits=24)),
                ("source_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("allocated_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorderoutput"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="production.productioncostallocationrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.productionoverheadsnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionTariff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("CUT", "Potong"),
                            ("SEW", "Jahit"),
                            ("QC_PACKING", "QC & Packing"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "wage_method",
                    models.CharField(
                        choices=[("PIECE_RATE", "Borongan"), ("NO_WAGE", "Tanpa Upah")],
                        max_length=16,
                    ),
                ),
                ("rate_per_unit", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="IDR", max_length=3)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionLaborCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_code_snapshot", models.CharField(blank=True, max_length=64)),
                ("employee_name_snapshot", models.CharField(blank=True, max_length=255)),
                (
                    "stage_snapshot",
                    models.CharField(
                        choices=[
                            ("CUT", "Potong"),
                            ("SEW", "Jahit"),
                            ("QC_PACKING", "QC & Packing"),
                        ],
                        max_length=16,
                    ),
                ),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("quantity_snapshot", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "wage_method",
                    models.CharField(
                        choices=[("PIECE_RATE", "Borongan"), ("NO_WAGE", "Tanpa Upah")],
                        max_length=16,
                    ),
                ),
                (
                    "tariff_rate_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("production_date", models.DateField()),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.employee",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorderoutput"
                    ),
                ),
                (
                    "source_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labor_costs",
                        to="production.productionworkline",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorder"
                    ),
                ),
                (
                    "tariff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.productiontariff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionCostSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("as_of_date", models.DateField()),
                (
                    "material_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "labor_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "direct_extra_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "overhead_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "total_cogm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "unit_hpp",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("status", models.CharField(default="INCOMPLETE", max_length=32)),
                ("component_status", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorderoutput"
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.productioncostsnapshot",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorder"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("output", "version"), name="prod_cost_snapshot_ver_uq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionDirectExtraCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cost_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MEAL_OPERATOR", "Makan Operator"),
                            ("DAILY_WAGE", "Upah Harian"),
                            ("ACCESSORY_ADVANCE", "Uang Muka Aksesoris"),
                            ("OTHER_DIRECT", "Lainnya Langsung"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("POSTED", "Posted")],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_production_extra_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.employee",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorderoutput"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_production_extra_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorder"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_productiondirectextracost", "Can post production direct extra cost")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="prod_extra_amount_pos"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="productiontariff",
            index=models.Index(
                fields=["legal_entity", "stage", "item"], name="prod_tariff_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productiontariff",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate_per_unit__gte", 0)), name="prod_tariff_rate_valid"
            ),
        ),
        migrations.AddIndex(
            model_name="productionlaborcost",
            index=models.Index(fields=["output", "reversed_at"], name="prod_labor_output_idx"),
        ),
    ]
