# Generated by Django 5.2.17 on 2026-08-27 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0004_productiondirectextracostreversal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productiondirectextracostreversal",
            name="replacement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_sources",
                to="production.productiondirectextracost",
            ),
        ),
        migrations.AddField(
            model_name="productionlaborcostreversal",
            name="replacement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal_sources",
                to="production.productionlaborcost",
            ),
        ),
        migrations.AddField(
            model_name="productionoverheadsnapshot",
            name="captured_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="captured_production_overheads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionoverheadsnapshot",
            name="source_reversal_status",
            field=models.CharField(default="ACTIVE", max_length=32),
        ),
    ]
