# Generated by Django 5.2.17 on 2026-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0005_productiondirectextracostreversal_replacement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionoverheadsnapshot",
            name="accounting_treatment_snapshot",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="productionoverheadsnapshot",
            name="category_snapshot",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="productionoverheadsnapshot",
            name="cost_center_snapshot",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
