# Generated by Django 5.2.17 on 2026-09-03 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_employee"),
        ("production", "0006_productionoverheadsnapshot_accounting_treatment_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionwarehousehandover",
            name="cpo_beneficiary",
            field=models.ForeignKey(
                blank=True,
                help_text="Explicit beneficiary/SPV for CPO Finished Goods Fee associated with this Production → Warehouse handover.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cpo_production_handovers",
                to="accounts.employee",
            ),
        ),
    ]
