# Generated by Django 5.2.17 on 2026-08-26 03:48

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_documentsequence_documentnumberallocation_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=120)),
                ("document_date", models.DateField()),
                ("customer_code_snapshot", models.CharField(max_length=40)),
                ("customer_name_snapshot", models.CharField(max_length=255)),
                ("customer_legal_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("customer_po_reference", models.CharField(blank=True, max_length=120)),
                ("requested_delivery_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="IDR", max_length=3)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("ON_HOLD", "On hold"),
                            ("CANCELLED", "Cancelled"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "freight_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="organizations.businessunit",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_sales_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_sales_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_sales_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "document_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order",
                        to="core.documentnumberallocation",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_orders",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ("-document_date", "-created_at"),
                "permissions": [
                    ("confirm_salesorder", "Can confirm sales order"),
                    ("cancel_salesorder", "Can cancel sales order"),
                    ("hold_salesorder", "Can hold or release sales order"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("description_snapshot", models.TextField(blank=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("AMOUNT", "Amount"), ("PERCENT", "Percent")],
                        default="AMOUNT",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=18),
                ),
                ("tax_classification_snapshot", models.CharField(blank=True, max_length=64)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=8),
                ),
                (
                    "line_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "line_discount_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "line_tax_base",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "line_tax_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "ordering": ("line_number", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["legal_entity", "state", "document_date"], name="sales_order_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(
                fields=["customer", "state", "document_date"], name="sales_order_customer_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"),
                name="sales_order_entity_document_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal__gte", 0),
                    ("discount_total__gte", 0),
                    ("tax_total__gte", 0),
                    ("freight_amount__gte", 0),
                    ("grand_total__gte", 0),
                ),
                name="sales_order_totals_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="salesorderline",
            index=models.Index(fields=["sales_order", "item"], name="sales_order_line_item_idx"),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.UniqueConstraint(
                fields=("sales_order", "line_number"), name="sales_order_line_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="sales_order_line_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="sales_order_line_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", 0)),
                name="sales_order_line_discount_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0)), name="sales_order_line_tax_nonnegative"
            ),
        ),
    ]
