# Generated by Django 5.2.17 on 2026-08-26 07:39

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_documentsequence_documentnumberallocation_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=120)),
                ("delivery_date", models.DateField()),
                ("customer_code_snapshot", models.CharField(max_length=40)),
                ("customer_name_snapshot", models.CharField(max_length=255)),
                ("customer_legal_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("destination_snapshot", models.TextField(blank=True)),
                ("expedition_reference", models.CharField(blank=True, max_length=160)),
                ("notes", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_sales_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_sales_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_deliveries",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "document_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_delivery",
                        to="core.documentnumberallocation",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_deliveries",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_sales_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-delivery_date", "-created_at"),
                "permissions": [
                    ("post_salesdelivery", "Can post sales delivery"),
                    ("cancel_salesdelivery", "Can cancel sales delivery"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesDeliveryLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                ("source_sales_order_number_snapshot", models.CharField(max_length=120)),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("description_snapshot", models.TextField(blank=True)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("ordered_quantity_snapshot", models.DecimalField(decimal_places=6, max_digits=18)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_delivery_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "sales_delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.salesdelivery",
                    ),
                ),
                (
                    "source_sales_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_lines",
                        to="sales.salesorderline",
                    ),
                ),
            ],
            options={
                "ordering": ("line_number", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=120)),
                ("invoice_date", models.DateField()),
                ("customer_code_snapshot", models.CharField(max_length=40)),
                ("customer_name_snapshot", models.CharField(max_length=255)),
                ("customer_legal_name_snapshot", models.CharField(blank=True, max_length=255)),
                (
                    "source_mode",
                    models.CharField(
                        choices=[
                            ("DELIVERY", "Delivery"),
                            ("SALES_ORDER", "Sales Order exception"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_kind",
                    models.CharField(
                        choices=[("INVOICE", "Invoice"), ("PROFORMA", "Proforma")],
                        default="INVOICE",
                        max_length=12,
                    ),
                ),
                ("source_exception_reason", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="IDR", max_length=3)),
                ("notes", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "freight_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_sales_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_sales_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_sales_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoices",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "document_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoice",
                        to="core.documentnumberallocation",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoices",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ("-invoice_date", "-created_at"),
                "permissions": [
                    ("confirm_salesinvoice", "Can confirm sales invoice source"),
                    ("cancel_salesinvoice", "Can cancel sales invoice source"),
                    ("create_salesorder_invoice", "Can create Sales Order based invoice source"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_number", models.PositiveIntegerField()),
                ("source_sales_order_number_snapshot", models.CharField(max_length=120)),
                (
                    "source_sales_delivery_number_snapshot",
                    models.CharField(blank=True, max_length=120),
                ),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("description_snapshot", models.TextField(blank=True)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("AMOUNT", "Amount"), ("PERCENT", "Percent")], max_length=10
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=18),
                ),
                ("tax_classification_snapshot", models.CharField(blank=True, max_length=64)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=8),
                ),
                (
                    "line_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "line_discount_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "line_tax_base",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "line_tax_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_invoice_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "sales_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "source_sales_delivery_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="sales.salesdeliveryline",
                    ),
                ),
                (
                    "source_sales_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="sales.salesorderline",
                    ),
                ),
            ],
            options={
                "ordering": ("line_number", "created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="salesdelivery",
            index=models.Index(
                fields=["legal_entity", "state", "delivery_date"], name="sales_delivery_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesdelivery",
            index=models.Index(
                fields=["customer", "state", "delivery_date"], name="sales_delivery_customer_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdelivery",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"), name="sales_del_entity_doc_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="salesdeliveryline",
            index=models.Index(
                fields=["source_sales_order_line", "sales_delivery"],
                name="sales_delivery_line_source_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdeliveryline",
            constraint=models.UniqueConstraint(
                fields=("sales_delivery", "line_number"), name="sales_del_line_no_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdeliveryline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="sales_del_line_qty_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesdeliveryline",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordered_quantity_snapshot__gt", 0)),
                name="sales_del_line_ordered_qty_pos",
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["legal_entity", "state", "invoice_date"], name="sales_invoice_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["customer", "state", "invoice_date"], name="sales_invoice_customer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["source_mode", "document_kind", "state"], name="sales_invoice_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"), name="sales_inv_entity_doc_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal__gte", 0),
                    ("discount_total__gte", 0),
                    ("tax_total__gte", 0),
                    ("freight_amount__gte", 0),
                    ("grand_total__gte", 0),
                ),
                name="sales_inv_totals_nonneg",
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoiceline",
            index=models.Index(
                fields=["source_sales_delivery_line", "sales_invoice"],
                name="sales_inv_line_delivery_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoiceline",
            index=models.Index(
                fields=["source_sales_order_line", "sales_invoice"], name="sales_inv_line_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.UniqueConstraint(
                fields=("sales_invoice", "line_number"), name="sales_inv_line_no_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="sales_inv_line_qty_pos"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="sales_inv_line_price_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gte", 0)),
                name="sales_inv_line_discount_nonneg",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_rate__gte", 0)), name="sales_inv_line_tax_nonneg"
            ),
        ),
    ]
