# Generated by Django 5.2.17 on 2026-08-26 13:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        ("sales", "0002_salesdelivery_salesdeliveryline_salesinvoice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrderCreditControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_AVAILABLE", "Finance source unavailable"),
                            ("NOT_CONFIGURED", "Credit limit not configured"),
                            ("PASSED", "Passed"),
                            ("HELD", "Held"),
                            ("OVERRIDDEN", "Overridden"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "credit_limit_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "outstanding_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("order_exposure_snapshot", models.DecimalField(decimal_places=2, max_digits=18)),
                ("source_available", models.BooleanField(default=False)),
                ("source_name", models.CharField(max_length=100)),
                ("evaluated_at", models.DateTimeField()),
                ("override_reason", models.TextField(blank=True)),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_credit_controls",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "evaluated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluated_sales_credit_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_credit_controls",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overridden_sales_credit_controls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_control",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("override_salesorder_credit", "Can override Sales Order credit hold")
                ],
                "indexes": [
                    models.Index(fields=["customer", "status"], name="sales_credit_customer_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("order_exposure_snapshot__gte", 0)),
                        name="sales_credit_order_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("credit_limit_snapshot__isnull", True),
                            ("credit_limit_snapshot__gte", 0),
                            _connector="OR",
                        ),
                        name="sales_credit_limit_nonneg",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("outstanding_snapshot__isnull", True),
                            ("outstanding_snapshot__gte", 0),
                            _connector="OR",
                        ),
                        name="sales_credit_outstanding_nonneg",
                    ),
                ],
            },
        ),
    ]
