# Generated by Django 5.2.17 on 2026-08-26 13:07

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0002_documentsequence_documentnumberallocation_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        ("purchasing", "0001_initial"),
        ("sales", "0002_salesdelivery_salesdeliveryline_salesinvoice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("project_type", models.CharField(blank=True, max_length=80)),
                ("contract_reference", models.CharField(blank=True, max_length=120)),
                ("start_date", models.DateField()),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ON_HOLD", "On hold"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="IDR", max_length=3)),
                (
                    "budget_total",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "target_margin_percent",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activated_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "document_allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project",
                        to="core.documentnumberallocation",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-start_date", "-created_at"),
                "permissions": [
                    ("activate_project", "Can activate project"),
                    ("hold_project", "Can hold or release project"),
                    ("complete_project", "Can complete project"),
                    ("cancel_project", "Can cancel project"),
                    ("link_project_salesorder", "Can link project Sales Orders"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectBudgetLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("PURCHASING", "Purchasing"),
                            ("MAKLUN", "Maklun"),
                            ("INTERNAL_PRODUCTION", "Internal production"),
                            ("LABOR", "Labor"),
                            ("FREIGHT", "Freight"),
                            ("PACKAGING", "Packaging"),
                            ("CPO_FEE", "CPO fee"),
                            ("SALES_FEE", "Sales fee"),
                            ("DIRECT_OVERHEAD", "Direct overhead"),
                            ("ALLOCATED_OVERHEAD", "Allocated overhead"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_budget_lines",
                        to="organizations.costcenter",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_budget_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="projects.project",
                    ),
                ),
                (
                    "purchase_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_budget_lines",
                        to="purchasing.purchasecategory",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ProjectSalesOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_project_sales_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_order_links",
                        to="projects.project",
                    ),
                ),
                (
                    "sales_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_link",
                        to="sales.salesorder",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["legal_entity", "state", "start_date"], name="project_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["customer", "state", "target_date"], name="project_customer_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "code"), name="project_entity_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("budget_total__gte", 0)), name="project_budget_total_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_date__isnull", True),
                    ("target_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="project_target_date_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_margin_percent__isnull", True),
                    models.Q(
                        ("target_margin_percent__gte", 0), ("target_margin_percent__lte", 100)
                    ),
                    _connector="OR",
                ),
                name="project_target_margin_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="projectbudgetline",
            index=models.Index(
                fields=["project", "category", "is_active"], name="project_budget_line_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectbudgetline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="project_budget_line_nonneg"
            ),
        ),
        migrations.AddIndex(
            model_name="projectsalesorder",
            index=models.Index(fields=["project", "sales_order"], name="project_so_link_idx"),
        ),
    ]
