# Generated by Django 5.2.17 on 2026-09-03 05:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("projects", "0001_phase_3c"),
        ("purchasing", "0004_phase_4b2"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectForecastLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MATERIAL", "Material"),
                            ("PURCHASING", "Purchasing"),
                            ("MAKLUN", "Maklun"),
                            ("INTERNAL_PRODUCTION", "Internal production"),
                            ("LABOR", "Labor"),
                            ("FREIGHT", "Freight"),
                            ("PACKAGING", "Packaging"),
                            ("CPO_FEE", "CPO fee"),
                            ("SALES_FEE", "Sales fee"),
                            ("DIRECT_OVERHEAD", "Direct overhead"),
                            ("ALLOCATED_OVERHEAD", "Allocated overhead"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_forecast_lines",
                        to="organizations.costcenter",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_forecast_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecast_lines",
                        to="projects.project",
                    ),
                ),
                (
                    "purchase_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_forecast_lines",
                        to="purchasing.purchasecategory",
                    ),
                ),
            ],
            options={
                "ordering": ("category", "created_at"),
                "indexes": [
                    models.Index(
                        fields=["project", "category", "is_active"],
                        name="project_forecast_line_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)), name="project_forecast_line_nonneg"
                    )
                ],
            },
        ),
    ]
