# Generated by Django 5.2.17 on 2026-09-03 07:17

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("projects", "0002_projectforecastline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveAccrual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "incentive_type",
                    models.CharField(
                        choices=[
                            ("CPO_FEE", "CPO Finished Goods Fee"),
                            ("SALES_COMMISSION", "Sales Commission / Sales Fee"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("source_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("source_module", models.CharField(max_length=32)),
                ("source_type", models.CharField(max_length=64)),
                ("source_document_id", models.CharField(max_length=64)),
                ("source_line_id", models.CharField(blank=True, max_length=64)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("accrual_date", models.DateField(db_index=True)),
                ("rule_code_snapshot", models.CharField(max_length=64)),
                ("trigger_snapshot", models.CharField(max_length=32)),
                ("calculation_method_snapshot", models.CharField(max_length=32)),
                ("rate_snapshot", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency_snapshot", models.CharField(default="IDR", max_length=3)),
                (
                    "basis_quantity",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "basis_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "beneficiary_type",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("PARTNER", "Business Partner"),
                            ("CUSTOM", "Custom Beneficiary"),
                        ],
                        max_length=32,
                    ),
                ),
                ("beneficiary_id", models.CharField(db_index=True, max_length=64)),
                ("beneficiary_code_snapshot", models.CharField(blank=True, max_length=64)),
                ("beneficiary_name_snapshot", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ESTIMATED", "Estimated"),
                            ("ACCRUED", "Accrued"),
                            ("APPROVED", "Approved"),
                            ("PAYABLE", "Payable"),
                            ("PAID", "Paid"),
                            ("REVERSED", "Reversed"),
                        ],
                        db_index=True,
                        default="ACCRUED",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incentive_accruals",
                        to="catalog.item",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incentive_accruals",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incentive_accruals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-accrual_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncentiveAccrualReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                ("reversed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accrual",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="incentives.incentiveaccrual",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reversed_at"],
            },
        ),
        migrations.CreateModel(
            name="IncentiveRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "incentive_type",
                    models.CharField(
                        choices=[
                            ("CPO_FEE", "CPO Finished Goods Fee"),
                            ("SALES_COMMISSION", "Sales Commission / Sales Fee"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("FINISHED_GOODS_ACCEPTED", "Finished Goods Accepted"),
                            ("INVOICE_POSTED", "Invoice Posted"),
                            ("INVOICE_PAID", "Invoice Paid"),
                            ("PROJECT_CLOSED", "Project Closed"),
                            ("APPROVED_CUSTOM_EVENT", "Approved Custom Event"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("PER_UNIT", "Per Unit"),
                            ("PERCENT_REVENUE", "% Revenue"),
                            ("PERCENT_MARGIN_PROFIT", "% Margin/Profit"),
                            ("FIXED", "Fixed"),
                            ("TIERED", "Tiered"),
                            ("APPROVED_FORMULA", "Approved Formula"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=18),
                ),
                ("currency", models.CharField(default="IDR", max_length=3)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional Item/SKU scope. Unscoped rules have item=None.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incentive_rules",
                        to="catalog.item",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incentive_rules",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "code"],
            },
        ),
        migrations.AddField(
            model_name="incentiveaccrual",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accruals",
                to="incentives.incentiverule",
            ),
        ),
        migrations.AddIndex(
            model_name="incentiverule",
            index=models.Index(
                fields=["legal_entity", "incentive_type", "trigger_type", "is_active"],
                name="idx_inc_rule_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="incentiverule",
            index=models.Index(fields=["legal_entity", "item"], name="idx_inc_rule_item"),
        ),
        migrations.AddConstraint(
            model_name="incentiverule",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate_value__gte", 0)), name="incentive_rule_rate_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="incentiverule",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "code"), name="unique_incentive_rule_code_per_entity"
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveaccrual",
            index=models.Index(
                fields=["legal_entity", "incentive_type", "state"], name="idx_inc_accrual_state"
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveaccrual",
            index=models.Index(
                fields=["legal_entity", "accrual_date"], name="idx_inc_accrual_date"
            ),
        ),
        migrations.AddIndex(
            model_name="incentiveaccrual",
            index=models.Index(fields=["project", "incentive_type"], name="idx_inc_accrual_proj"),
        ),
        migrations.AddConstraint(
            model_name="incentiveaccrual",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="incentive_accrual_amount_non_negative"
            ),
        ),
    ]
