# Generated by Django 5.2.17 on 2026-09-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incentives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incentiveaccrual",
            name="basis_quantity",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
