# Generated by Django 5.2.17 on 2026-08-26 01:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("import_type", models.CharField(max_length=50)),
                ("template_version", models.CharField(max_length=20)),
                ("source_filename", models.CharField(max_length=255)),
                ("source_system", models.CharField(blank=True, max_length=80)),
                ("checksum", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("VALIDATED_WITH_ERRORS", "Validated with errors"),
                            ("READY_TO_IMPORT", "Ready to import"),
                            ("IMPORTED", "Imported"),
                            ("PARTIAL_FAILED", "Partial failed"),
                        ],
                        default="UPLOADED",
                        max_length=30,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("replay_count", models.PositiveIntegerField(default=0)),
                ("last_replayed_at", models.DateTimeField(blank=True, null=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("warning_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ImportRowResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                ("normalized_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("IMPORTED", "Imported"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("messages", models.JSONField(blank=True, default=list)),
                ("target_reference", models.CharField(blank=True, max_length=255)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="data_exchange.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ("row_number",),
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["legal_entity", "import_type", "status"],
                name="data_import_scope_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "import_type", "checksum"),
                name="data_import_entity_type_checksum_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="importrowresult",
            index=models.Index(fields=["batch", "status"], name="data_import_row_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="importrowresult",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="data_import_row_batch_number_unique"
            ),
        ),
    ]
