# Generated by Django 5.2.17 on 2026-08-26 01:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="COAAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("account_code", models.CharField(max_length=40)),
                ("account_code_normalized", models.CharField(editable=False, max_length=40)),
                ("account_name", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                            ("COGS", "COGS"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("report_group", models.CharField(blank=True, max_length=80)),
                ("report_subgroup", models.CharField(blank=True, max_length=80)),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], max_length=10
                    ),
                ),
                ("is_header", models.BooleanField(default=False)),
                ("is_posting_allowed", models.BooleanField(default=True)),
                ("manual_journal_allowed", models.BooleanField(default=False)),
                ("is_cash_bank", models.BooleanField(default=False)),
                ("is_control_account", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coa_accounts",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance.coaaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("legal_entity__code", "account_code"),
            },
        ),
        migrations.CreateModel(
            name="COAMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("module_code", models.CharField(max_length=40)),
                ("event_code", models.CharField(max_length=80)),
                (
                    "dimension_type",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("STORE", "Store"),
                            ("PURCHASE_CATEGORY", "Purchase category"),
                            ("COST_CENTER", "Cost center"),
                            ("PAYMENT_METHOD", "Payment method"),
                            ("TAX", "Tax"),
                            ("BUSINESS_UNIT", "Business unit"),
                            ("PROJECT", "Project"),
                        ],
                        max_length=30,
                    ),
                ),
                ("dimension_value", models.CharField(max_length=120)),
                ("dimension_value_normalized", models.CharField(editable=False, max_length=120)),
                ("line_role", models.CharField(max_length=80)),
                (
                    "dc",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")], max_length=10
                    ),
                ),
                ("priority", models.IntegerField(default=100)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coa_mappings",
                        to="finance.coaaccount",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coa_mappings",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "legal_entity__code",
                    "module_code",
                    "event_code",
                    "line_role",
                    "-priority",
                ),
            },
        ),
        migrations.AddIndex(
            model_name="coaaccount",
            index=models.Index(
                fields=["legal_entity", "account_code_normalized", "is_active"],
                name="finance_coa_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coaaccount",
            index=models.Index(fields=["parent", "is_active"], name="finance_coa_parent_idx"),
        ),
        migrations.AddConstraint(
            model_name="coaaccount",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "account_code_normalized", "effective_from"),
                name="finance_coa_entity_code_start_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="coaaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="finance_coaaccount_effective_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="coaaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_header", False), ("is_posting_allowed", False), _connector="OR"
                ),
                name="finance_coa_header_not_posting",
            ),
        ),
        migrations.AddIndex(
            model_name="coamapping",
            index=models.Index(
                fields=[
                    "legal_entity",
                    "module_code",
                    "event_code",
                    "line_role",
                    "dc",
                    "is_active",
                ],
                name="finance_mapping_resolve_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coamapping",
            index=models.Index(
                fields=["dimension_type", "dimension_value_normalized"],
                name="finance_mapping_dimension_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="coamapping",
            constraint=models.UniqueConstraint(
                fields=(
                    "legal_entity",
                    "module_code",
                    "event_code",
                    "dimension_type",
                    "dimension_value_normalized",
                    "line_role",
                    "dc",
                    "priority",
                    "effective_from",
                ),
                name="finance_mapping_scope_start_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="coamapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="finance_coamapping_effective_period_valid",
            ),
        ),
    ]
