# Generated by Django 5.2.17 on 2026-09-01 15:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
        ("finance", "0002_journalentry_journalline_payableentry_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coamapping",
            name="dimension_type",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Default"),
                    ("STORE", "Store"),
                    ("PURCHASE_CATEGORY", "Purchase category"),
                    ("COST_CENTER", "Cost center"),
                    ("PAYMENT_METHOD", "Payment method"),
                    ("TAX", "Tax"),
                    ("BUSINESS_UNIT", "Business unit"),
                    ("PROJECT", "Project"),
                    ("LIQUIDITY_ACCOUNT", "Liquidity account"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="LiquidityAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(choices=[("CASH", "Cash"), ("BANK", "Bank")], max_length=10),
                ),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("mapping_key", models.CharField(max_length=120)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("bank_account_number", models.CharField(blank=True, max_length=120)),
                ("account_holder_name", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidity_accounts",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "permissions": [("manage_liquidityaccount", "Can manage liquidity accounts")],
            },
        ),
        migrations.CreateModel(
            name="LiquidityEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField()),
                (
                    "direction",
                    models.CharField(choices=[("IN", "In"), ("OUT", "Out")], max_length=3),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("source_module", models.CharField(max_length=40)),
                ("source_document_type", models.CharField(max_length=80)),
                ("source_document_id", models.CharField(max_length=80)),
                ("source_key", models.CharField(max_length=255)),
                ("source_reference", models.JSONField(blank=True, default=dict)),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidity_entries",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "liquidity_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="finance.liquidityaccount",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.liquidityentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payment_number", models.CharField(max_length=80)),
                ("payment_date", models.DateField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("RECEIPT", "Receipt"), ("DISBURSEMENT", "Disbursement")],
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("source_module", models.CharField(max_length=40)),
                ("source_document_type", models.CharField(max_length=80)),
                ("source_document_id", models.CharField(max_length=80)),
                ("source_key", models.CharField(max_length=255)),
                ("source_reference", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[("POSTED", "Posted"), ("REVERSED", "Reversed")],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "liquidity_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.liquidityaccount",
                    ),
                ),
                (
                    "liquidity_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="finance.liquidityentry",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.payment",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="channels.store",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_payment", "Can post payment"),
                    ("reverse_payment", "Can reverse payment"),
                    ("view_cash", "Can view cash ledger"),
                    ("view_bank", "Can view bank ledger"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "payable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="finance.payableentry",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance.payment",
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="finance.receivableentry",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="liquidityaccount",
            index=models.Index(
                fields=["legal_entity", "account_type", "is_active"],
                name="finance_liquidity_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidityaccount",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "code"), name="finance_liquidity_account_code_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidityaccount",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "mapping_key"), name="finance_liquidity_mapping_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidityaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="finance_liquidity_effective_period_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="liquidityentry",
            index=models.Index(
                fields=["liquidity_account", "transaction_date"],
                name="finance_liquidity_ledger_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="liquidityentry",
            index=models.Index(
                fields=["legal_entity", "source_key"], name="finance_liquidity_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidityentry",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_key"), name="finance_liquidity_source_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidityentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_liquidity_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["legal_entity", "payment_date", "direction"],
                name="finance_payment_list_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_key"), name="finance_payment_source_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_payment_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_payment_alloc_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("payable__isnull", True), ("receivable__isnull", False)),
                    models.Q(("payable__isnull", False), ("receivable__isnull", True)),
                    _connector="OR",
                ),
                name="finance_payment_alloc_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "receivable"), name="finance_payment_alloc_receivable_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentallocation",
            constraint=models.UniqueConstraint(
                fields=("payment", "payable"), name="finance_payment_alloc_payable_uq"
            ),
        ),
    ]
