# Generated by Django 5.2.17 on 2026-09-02 02:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
        ("finance", "0003_alter_coamapping_dimension_type_liquidityaccount_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceBalanceEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField()),
                (
                    "direction",
                    models.CharField(choices=[("IN", "In"), ("OUT", "Out")], max_length=3),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("source_module", models.CharField(max_length=40)),
                ("source_document_type", models.CharField(max_length=80)),
                ("source_document_id", models.CharField(max_length=80)),
                ("source_key", models.CharField(max_length=255)),
                ("source_reference", models.JSONField(blank=True, default=dict)),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_balance_entries",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.marketplacebalanceentry",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_balance_entries",
                        to="channels.store",
                    ),
                ),
            ],
            options={
                "permissions": [("view_marketplace_balance", "Can view marketplace balance")],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceSettlementPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_settlement_id", models.CharField(max_length=80)),
                ("source_settlement_identity", models.CharField(max_length=500)),
                ("settlement_date", models.DateField()),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("ar_cleared_amount", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "marketplace_balance_amount",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                ("fee_amount", models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ("fee_components", models.JSONField(blank=True, default=dict)),
                ("source_reference", models.JSONField(blank=True, default=dict)),
                ("source_lineage", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[("POSTED", "Posted"), ("REVERSED", "Reversed")],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_settlement_posting",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_settlement_postings",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "marketplace_balance_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_settlement_posting",
                        to="finance.marketplacebalanceentry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.receivableentry"
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.marketplacesettlementposting",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="channels.store"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_marketplace_settlement", "Can view marketplace settlements"),
                    ("post_marketplace_settlement", "Can post marketplace settlements"),
                    ("reverse_marketplace_settlement", "Can reverse marketplace settlements"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="marketplacebalanceentry",
            index=models.Index(
                fields=["legal_entity", "store", "transaction_date"],
                name="fin_mkt_balance_ledger_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacebalanceentry",
            index=models.Index(
                fields=["legal_entity", "source_key"], name="fin_mkt_balance_source_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacebalanceentry",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_key"), name="finance_marketplace_balance_source_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacebalanceentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="finance_marketplace_balance_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplacesettlementposting",
            index=models.Index(
                fields=["legal_entity", "store", "settlement_date"],
                name="fin_mkt_settlement_list_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacesettlementposting",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_settlement_identity"),
                name="finance_marketplace_settlement_source_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacesettlementposting",
            constraint=models.CheckConstraint(
                condition=models.Q(("ar_cleared_amount__gt", 0)),
                name="finance_marketplace_settlement_ar_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacesettlementposting",
            constraint=models.CheckConstraint(
                condition=models.Q(("marketplace_balance_amount__gt", 0)),
                name="finance_marketplace_settlement_balance_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="marketplacesettlementposting",
            constraint=models.CheckConstraint(
                condition=models.Q(("fee_amount__gte", 0)),
                name="finance_marketplace_settlement_fee_nonnegative",
            ),
        ),
    ]
