# Generated by Django 5.2.17 on 2026-09-02 03:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("channels", "0001_initial"),
        ("finance", "0004_marketplacebalanceentry_marketplacesettlementposting_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceAdjustmentPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_adjustment_id", models.CharField(max_length=80)),
                ("source_adjustment_identity", models.CharField(max_length=500)),
                ("transaction_date", models.DateField()),
                ("signed_amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CONSUMED_IN_SETTLEMENT", "Consumed in settlement"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="CONSUMED_IN_SETTLEMENT",
                        max_length=32,
                    ),
                ),
                ("source_reference", models.JSONField(blank=True, default=dict)),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_adjustment_postings",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.marketplaceadjustmentposting",
                    ),
                ),
                (
                    "settlement_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_postings",
                        to="finance.marketplacesettlementposting",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="channels.store"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["legal_entity", "store", "transaction_date"],
                        name="fin_mkt_adjustment_list_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "source_adjustment_identity"),
                        name="finance_mkt_adjustment_source_uq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketplacePayoutPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_payout_id", models.CharField(max_length=80)),
                ("source_payout_identity", models.CharField(max_length=500)),
                ("payout_reference", models.CharField(max_length=180)),
                ("payout_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                (
                    "state",
                    models.CharField(
                        choices=[("POSTED", "Posted"), ("REVERSED", "Reversed")],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("source_reference", models.JSONField(blank=True, default=dict)),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_payout_posting",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "liquidity_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.liquidityaccount"
                    ),
                ),
                (
                    "liquidity_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_payout_posting",
                        to="finance.liquidityentry",
                    ),
                ),
                (
                    "marketplace_balance_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_payout_posting",
                        to="finance.marketplacebalanceentry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.marketplacepayoutposting",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="channels.store"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["legal_entity", "store", "payout_date"],
                        name="fin_mkt_payout_list_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "source_payout_identity"),
                        name="finance_mkt_payout_source_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="finance_mkt_payout_amount_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceReturnPosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_return_id", models.CharField(max_length=80)),
                ("source_return_identity", models.CharField(max_length=500)),
                ("transaction_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("RECEIVABLE_CREDIT", "Receivable credit"),
                            ("MARKETPLACE_BALANCE_CREDIT", "Marketplace balance credit"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("POSTED", "Posted"), ("REVERSED", "Reversed")],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("source_reference", models.JSONField(blank=True, default=dict)),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_return_posting",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "marketplace_balance_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_return_posting",
                        to="finance.marketplacebalanceentry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receivable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.receivableentry"
                    ),
                ),
                (
                    "revenue_journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.journalentry"
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.marketplacereturnposting",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="channels.store"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["legal_entity", "store", "transaction_date"],
                        name="fin_mkt_return_list_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "source_return_identity"),
                        name="finance_mkt_return_source_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="finance_mkt_return_amount_positive",
                    ),
                ],
            },
        ),
    ]
