# Generated by Django 5.2.17 on 2026-09-02 10:51

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_marketplaceadjustmentposting_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=150)),
                ("mapping_key", models.CharField(max_length=120)),
                (
                    "default_depreciation_method",
                    models.CharField(
                        choices=[("STRAIGHT_LINE", "Straight line")],
                        default="STRAIGHT_LINE",
                        max_length=30,
                    ),
                ),
                ("default_useful_life_months", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_number", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("acquisition_date", models.DateField()),
                ("capitalization_date", models.DateField()),
                ("acquisition_cost", models.DecimalField(decimal_places=0, max_digits=20)),
                ("residual_value", models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ("useful_life_months", models.PositiveIntegerField()),
                (
                    "depreciation_method",
                    models.CharField(choices=[("STRAIGHT_LINE", "Straight line")], max_length=30),
                ),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("source_module", models.CharField(max_length=40)),
                ("source_document_type", models.CharField(max_length=80)),
                ("source_document_id", models.CharField(max_length=80)),
                ("source_key", models.CharField(max_length=255)),
                ("source_reference", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FULLY_DEPRECIATED", "Fully depreciated"),
                            ("DISPOSED", "Disposed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="ACTIVE",
                        max_length=24,
                    ),
                ),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.assetclass"
                    ),
                ),
                (
                    "capitalization_journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.journalentry"
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("capitalize_fixedasset", "Can capitalize fixed assets")],
            },
        ),
        migrations.CreateModel(
            name="DepreciationScheduleEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_date", models.DateField()),
                ("scheduled_amount", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="SCHEDULED",
                        max_length=16,
                    ),
                ),
                ("source_key", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.journalentry",
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.depreciationscheduleentry",
                    ),
                ),
                (
                    "fixed_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_entries",
                        to="finance.fixedasset",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_depreciation", "Can view depreciation"),
                    ("post_depreciation", "Can post depreciation"),
                    ("reverse_depreciation", "Can reverse depreciation"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="assetclass",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "code"), name="finance_asset_class_code_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="assetclass",
            constraint=models.CheckConstraint(
                condition=models.Q(("default_useful_life_months__gt", 0)),
                name="finance_asset_class_life_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "asset_number"), name="finance_fixed_asset_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_key"), name="finance_fixed_asset_source_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("acquisition_cost__gt", 0)),
                name="finance_fixed_asset_cost_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("residual_value__gte", 0)),
                name="finance_fixed_asset_residual_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationscheduleentry",
            constraint=models.UniqueConstraint(
                fields=("fixed_asset", "period_date"), name="finance_depr_asset_period_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationscheduleentry",
            constraint=models.UniqueConstraint(
                fields=("source_key",), name="finance_depr_source_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationscheduleentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("scheduled_amount__gt", 0)), name="finance_depr_amount_positive"
            ),
        ),
    ]
