# Generated by Django 5.2.17 on 2026-09-02 13:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_assetclass_fixedasset_depreciationscheduleentry_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fiscal_year", models.PositiveIntegerField()),
                ("period_number", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_periods",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("manage_accountingperiod", "Can manage accounting period"),
                    ("close_accountingperiod", "Can close accounting period"),
                ],
                "indexes": [
                    models.Index(
                        fields=["legal_entity", "start_date", "end_date"],
                        name="finance_period_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "fiscal_year", "period_number"),
                        name="finance_period_number_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="finance_period_dates_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WagePayableAccrual",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_module", models.CharField(max_length=40)),
                ("source_type", models.CharField(max_length=80)),
                ("source_id", models.CharField(max_length=80)),
                ("source_key", models.CharField(max_length=255)),
                ("source_reference", models.JSONField(default=dict)),
                ("production_lineage", models.JSONField(default=dict)),
                ("beneficiary_reference", models.CharField(blank=True, max_length=120)),
                ("accrual_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("debit_line_role", models.CharField(max_length=80)),
                ("mapping_context", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[("POSTED", "Posted"), ("REVERSED", "Reversed")],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wage_accrual",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "payable_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wage_accrual",
                        to="finance.payableentry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.wagepayableaccrual",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_wagepayable", "Can post wage payable"),
                    ("reverse_wagepayable", "Can reverse wage payable"),
                ],
                "indexes": [
                    models.Index(
                        fields=["legal_entity", "accrual_date"], name="finance_wage_list_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "source_key"), name="finance_wage_source_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="finance_wage_amount_positive"
                    ),
                ],
            },
        ),
    ]
