# Generated by Django 5.2.17 on 2026-09-02 13:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0007_wage_payable_and_period_controls"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("statement_reference", models.CharField(max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("currency", models.CharField(default="IDR", max_length=12)),
                (
                    "opening_balance",
                    models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
                ),
                (
                    "closing_balance",
                    models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
                ),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("source_checksum", models.CharField(blank=True, max_length=128)),
                (
                    "state",
                    models.CharField(choices=[("OPEN", "Open")], default="OPEN", max_length=12),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "liquidity_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finance.liquidityaccount"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("manage_bankstatement", "Can manage bank statement"),
                    ("match_bankstatement", "Can match bank statement"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BankStatementLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_identity", models.CharField(max_length=255)),
                ("transaction_date", models.DateField()),
                ("value_date", models.DateField(blank=True, null=True)),
                ("external_reference", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "direction",
                    models.CharField(choices=[("IN", "In"), ("OUT", "Out")], max_length=3),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "running_balance",
                    models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="finance.bankstatement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankReconciliationMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("matched_amount", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVERSED", "Reversed")],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("reason", models.TextField(blank=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "liquidity_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_matches",
                        to="finance.liquidityentry",
                    ),
                ),
                (
                    "matched_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_bank_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bank_statement_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="finance.bankstatementline",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="bankstatement",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "liquidity_account", "statement_reference"),
                name="finance_bank_statement_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatementline",
            constraint=models.UniqueConstraint(
                fields=("statement", "source_identity"), name="finance_bank_line_source_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatementline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="finance_bank_line_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankreconciliationmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("matched_amount__gt", 0)), name="finance_bank_match_positive"
            ),
        ),
    ]
