# Generated by Django 5.2.17 on 2026-09-03 10:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_bank_reconciliation"),
        ("incentives", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentivePayablePosting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("incentive_type_snapshot", models.CharField(max_length=40)),
                ("source_key", models.CharField(max_length=255)),
                ("accounting_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("beneficiary_type", models.CharField(blank=True, max_length=40)),
                ("beneficiary_id", models.CharField(blank=True, max_length=64)),
                ("beneficiary_code_snapshot", models.CharField(blank=True, max_length=64)),
                ("beneficiary_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("project_reference", models.CharField(blank=True, max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[("POSTED", "Posted"), ("REVERSED", "Reversed")],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "incentive_accrual",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_posting",
                        to="incentives.incentiveaccrual",
                    ),
                ),
                (
                    "journal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incentive_posting",
                        to="finance.journalentry",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "payable_entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incentive_posting",
                        to="finance.payableentry",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="finance.incentivepayableposting",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["legal_entity", "accounting_date"], name="finance_inc_post_date_idx"
                    ),
                    models.Index(
                        fields=["incentive_type_snapshot", "state"],
                        name="finance_inc_post_type_st_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "source_key"),
                        name="finance_incentive_posting_source_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="finance_incentive_posting_amount_positive",
                    ),
                ],
            },
        ),
    ]
