# Generated by Django 5.2.17 on 2026-08-25 12:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.CharField(max_length=255)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("correlation_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(blank=True)),
                ("approval_reference", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(blank=True, db_index=True, max_length=255)),
                ("before_state", models.JSONField(blank=True, null=True)),
                ("after_state", models.JSONField(blank=True, null=True)),
                ("changed_fields", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["target_type", "target_id"], name="core_audit_target_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("namespace", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=255)),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("result_reference", models.CharField(blank=True, max_length=255)),
                ("response", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
                "indexes": [
                    models.Index(fields=["namespace", "status"], name="core_idem_scope_status_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("namespace", "key"), name="core_idempotency_namespace_key_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("finished_at__isnull", True), ("status", "IN_PROGRESS")),
                            models.Q(
                                ("finished_at__isnull", False),
                                ("status__in", ("COMPLETED", "FAILED")),
                            ),
                            _connector="OR",
                        ),
                        name="core_idempotency_finish_state_valid",
                    ),
                ],
            },
        ),
    ]
