# Generated by Django 5.2.17 on 2026-08-25 15:17

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("document_type", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                ("prefix", models.CharField(blank=True, max_length=32)),
                (
                    "format_template",
                    models.CharField(
                        default="{prefix}{yyyymmdd}-{seq}",
                        help_text="Allowed tokens: {prefix}, {yyyy}, {yy}, {mm}, {dd}, {yyyymmdd}, {yymmdd}, and exactly one {seq}.",
                        max_length=120,
                    ),
                ),
                ("padding", models.PositiveSmallIntegerField(default=4)),
                ("starting_number", models.PositiveBigIntegerField(default=1)),
                (
                    "reset_mode",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("YEARLY", "Yearly"),
                            ("MONTHLY", "Monthly"),
                            ("DAILY", "Daily"),
                        ],
                        default="DAILY",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_sequences",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ("legal_entity__code", "document_type", "-effective_from"),
            },
        ),
        migrations.CreateModel(
            name="DocumentNumberAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("document_type", models.CharField(max_length=64)),
                ("business_date", models.DateField()),
                ("period_key", models.CharField(max_length=16)),
                ("sequence_value", models.PositiveBigIntegerField()),
                ("number", models.CharField(max_length=120)),
                ("request_key", models.CharField(blank=True, max_length=120)),
                ("allocated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_number_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_number_allocations",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="core.documentsequence",
                    ),
                ),
            ],
            options={
                "ordering": ("-allocated_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentSequenceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_key", models.CharField(max_length=16)),
                ("last_value", models.PositiveBigIntegerField(default=0)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="states",
                        to="core.documentsequence",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="documentsequence",
            index=models.Index(
                fields=["legal_entity", "document_type", "is_active"],
                name="core_sequence_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_type", "effective_from"),
                name="core_sequence_entity_type_start_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.CheckConstraint(
                condition=models.Q(("padding__gte", 1), ("padding__lte", 12)),
                name="core_sequence_padding_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.CheckConstraint(
                condition=models.Q(("starting_number__gte", 1)),
                name="core_sequence_starting_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="core_documentsequence_effective_period_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="documentnumberallocation",
            index=models.Index(
                fields=["legal_entity", "document_type", "business_date"],
                name="core_docnum_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentnumberallocation",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "number"), name="core_document_number_entity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentnumberallocation",
            constraint=models.UniqueConstraint(
                fields=("sequence", "period_key", "sequence_value"),
                name="core_document_number_value_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentnumberallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("request_key", ""), _negated=True),
                fields=("legal_entity", "document_type", "request_key"),
                name="core_document_number_request_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsequencestate",
            constraint=models.UniqueConstraint(
                fields=("sequence", "period_key"), name="core_sequence_state_period_unique"
            ),
        ),
    ]
