# Generated by Django 5.2.17 on 2026-08-27 15:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("production", "0006_productionoverheadsnapshot_accounting_treatment_snapshot_and_more"),
        ("purchasing", "0004_phase_4b2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehousePostingSequence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("singleton", models.BooleanField(default=True, unique=True)),
                ("last_sequence", models.BigIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WarehouseMaterialIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("issue_date", models.DateField()),
                ("source_module", models.CharField(default="production", max_length=64)),
                ("source_type", models.CharField(default="MATERIAL_REQUEST", max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_warehouse_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_warehouse_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorder"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WarehouseReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receipt_date", models.DateField()),
                ("source_module", models.CharField(default="production", max_length=64)),
                ("source_type", models.CharField(default="PRODUCTION_HANDOVER", max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_warehouse_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handover",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.productionwarehousehandover",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_warehouse_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorder"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryValuationState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "inventory_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "average_unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "valuation_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("PENDING_VALUATION", "Menunggu Valuasi"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="READY",
                        max_length=24,
                    ),
                ),
                ("last_movement_sequence", models.BigIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_valuation_states",
                        to="catalog.item",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_states",
                        to="organizations.warehouse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["legal_entity", "warehouse"], name="wh_val_entity_wh_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "warehouse", "item"), name="wh_val_state_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity_on_hand__gte", 0)),
                        name="wh_val_qty_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(choices=[("IN", "Masuk"), ("OUT", "Keluar")], max_length=3),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PRODUCTION_MATERIAL_ISSUE", "Issue Bahan Produksi"),
                            ("PRODUCTION_FINISHED_GOODS_RECEIPT", "Terima Hasil Produksi"),
                        ],
                        max_length=48,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "valuation_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("PENDING_VALUATION", "Menunggu Valuasi"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="READY",
                        max_length=24,
                    ),
                ),
                ("source_module", models.CharField(max_length=64)),
                ("source_type", models.CharField(max_length=64)),
                ("source_document_id", models.CharField(max_length=64)),
                ("source_line_id", models.CharField(max_length=64)),
                ("source_key", models.CharField(max_length=255)),
                ("transaction_date", models.DateField()),
                ("posting_sequence", models.BigIntegerField(unique=True)),
                ("posted_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="POSTED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_movements",
                        to="catalog.item",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_movements",
                        to="warehouse.stockmovement",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="organizations.warehouse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["legal_entity", "warehouse", "item", "posting_sequence"],
                        name="wh_move_ledger_idx",
                    ),
                    models.Index(fields=["source_key", "state"], name="wh_move_source_state_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="wh_move_qty_positive"
                    ),
                    models.UniqueConstraint(
                        fields=("legal_entity", "source_key", "direction", "movement_type"),
                        name="wh_move_source_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseMaterialIssueLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_key", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.workordermaterialallocation",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.warehousematerialissue",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorderoutput"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["allocation"], name="wh_issue_alloc_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issue", "sequence"), name="wh_issue_line_seq_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="wh_issue_qty_positive"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_key", models.CharField(max_length=255)),
                ("accepted_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                (
                    "valuation_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("PENDING_VALUATION", "Menunggu Valuasi"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING_VALUATION",
                        max_length=24,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "handover_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="production.productionwarehousehandoverline",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.workorderoutput"
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.warehousereceipt",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["handover_line"], name="wh_receipt_handover_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("receipt", "sequence"), name="wh_receipt_line_seq_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("accepted_quantity__gt", 0)),
                        name="wh_receipt_qty_positive",
                    ),
                ],
            },
        ),
    ]
