# Generated by Django 5.2.17 on 2026-08-28 08:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
        ("projects", "0001_phase_3c"),
        ("purchasing", "0004_phase_4b2"),
        ("sales", "0003_phase_3c"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("PRODUCTION_MATERIAL_ISSUE", "Issue Bahan Produksi"),
                    ("PRODUCTION_FINISHED_GOODS_RECEIPT", "Terima Hasil Produksi"),
                    ("PURCHASE_RECEIPT", "Penerimaan Pembelian"),
                    ("SUBCONTRACT_RECEIPT", "Penerimaan Maklun"),
                    ("SALES_DELIVERY_ISSUE", "Pengeluaran Penjualan"),
                    ("OPNAME_GAIN", "Stock Opname Gain"),
                    ("OPNAME_LOSS", "Stock Opname Loss"),
                    ("INVENTORY_ADJUSTMENT", "Penyesuaian Stok"),
                    ("INTERNAL_CONSUMPTION", "Pemakaian Internal"),
                    ("SUPPLIER_RETURN", "Retur Supplier"),
                ],
                max_length=48,
            ),
        ),
        migrations.CreateModel(
            name="InternalConsumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField()),
                ("purpose", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organizations.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_internal_consumptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_internal_consumptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="projects.project",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adjustment_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COUNTED", "Counted"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("VOID", "Void"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("reason", models.TextField()),
                ("reference", models.CharField(max_length=255)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_inventory_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("approve_inventoryadjustment", "Can approve inventory adjustment"),
                    ("post_inventoryadjustment", "Can post inventory adjustment"),
                    ("reverse_inventoryadjustment", "Can reverse inventory adjustment"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("count_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COUNTED", "Counted"),
                            ("APPROVED", "Approved"),
                            ("POSTED", "Posted"),
                            ("VOID", "Void"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("snapshot_sequence", models.BigIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("approve_stockcount", "Can approve stock count"),
                    ("post_stockcount", "Can post stock count"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("system_qty_snapshot", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "counted_qty",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "variance_qty",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.stockcount",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_date", models.DateField()),
                ("reason", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_supplier_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_supplier_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="partners.businesspartner"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WarehousePurchaseReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vendor_code_snapshot", models.CharField(max_length=40)),
                ("vendor_name_snapshot", models.CharField(max_length=255)),
                ("receipt_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_warehouse_purchase_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_warehouse_purchase_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="purchasing.purchaseorder"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="partners.businesspartner"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_warehousepurchasereceipt", "Can post Warehouse purchase receipt"),
                    ("reverse_warehousepurchasereceipt", "Can reverse Warehouse purchase receipt"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehousePurchaseReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("purchase_category_code_snapshot", models.CharField(max_length=50)),
                ("purchase_category_name_snapshot", models.CharField(max_length=150)),
                ("accounting_treatment_snapshot", models.CharField(max_length=20)),
                ("vendor_id_snapshot", models.CharField(max_length=64)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("unit_cost_snapshot", models.DecimalField(decimal_places=6, max_digits=24)),
                ("total_value_snapshot", models.DecimalField(decimal_places=6, max_digits=24)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "posted_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_receipt_line",
                        to="warehouse.stockmovement",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_receipt_lines",
                        to="purchasing.purchaseorderline",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.warehousepurchasereceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "posted_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_return_line",
                        to="warehouse.stockmovement",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.purchaseorderline",
                    ),
                ),
                (
                    "supplier_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.supplierreturn",
                    ),
                ),
                (
                    "purchase_receipt_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.warehousepurchasereceiptline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarehouseSalesIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_code_snapshot", models.CharField(max_length=40)),
                ("customer_name_snapshot", models.CharField(max_length=255)),
                ("issue_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_warehouse_sales_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="partners.businesspartner"
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_warehouse_sales_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sales.salesdelivery"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_warehousesalesissue", "Can post Warehouse sales issue"),
                    ("reverse_warehousesalesissue", "Can reverse Warehouse sales issue"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseSalesIssueLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sales_order_id_snapshot", models.CharField(max_length=64)),
                ("sales_order_line_id_snapshot", models.CharField(max_length=64)),
                ("delivery_id_snapshot", models.CharField(max_length=64)),
                ("delivery_line_id_snapshot", models.CharField(max_length=64)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.warehousesalesissue",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "posted_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_issue_line",
                        to="warehouse.stockmovement",
                    ),
                ),
                (
                    "sales_delivery_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_issue_lines",
                        to="sales.salesdeliveryline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarehouseSubcontractReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vendor_code_snapshot", models.CharField(max_length=40)),
                ("vendor_name_snapshot", models.CharField(max_length=255)),
                ("receipt_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_warehouse_subcontract_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_warehouse_subcontract_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcontract_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.subcontractreceipt",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="partners.businesspartner"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.warehouse"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_warehousesubcontractreceipt", "Can post Warehouse subcontract receipt"),
                    (
                        "reverse_warehousesubcontractreceipt",
                        "Can reverse Warehouse subcontract receipt",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseSubcontractReceiptLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "quality_pass_quantity_snapshot",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "valuation_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("PENDING_VALUATION", "Menunggu Valuasi"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING_VALUATION",
                        max_length=24,
                    ),
                ),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "posted_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontract_receipt_line",
                        to="warehouse.stockmovement",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.warehousesubcontractreceipt",
                    ),
                ),
                (
                    "subcontract_receipt_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_receipt_lines",
                        to="purchasing.subcontractreceiptoutputline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternalConsumptionLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "consumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.internalconsumption",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "posted_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internal_consumption_line",
                        to="warehouse.stockmovement",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumption", "sequence"), name="wh_internal_line_seq_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="wh_internal_qty_positive"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryAdjustmentLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(choices=[("IN", "Masuk"), ("OUT", "Keluar")], max_length=3),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("cost_treatment", models.CharField(max_length=40)),
                (
                    "unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "total_value",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="warehouse.inventoryadjustment",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "posted_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_line",
                        to="warehouse.stockmovement",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("adjustment", "sequence"), name="wh_adjust_line_seq_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="wh_adjust_qty_positive"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stockcount",
            index=models.Index(
                fields=["legal_entity", "warehouse", "state", "count_date"],
                name="wh_count_list_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(fields=("count", "item"), name="wh_count_item_uq"),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                fields=("count", "sequence"), name="wh_count_line_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(("system_qty_snapshot__gte", 0)),
                name="wh_count_system_qty_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("counted_qty__isnull", True), ("counted_qty__gte", 0), _connector="OR"
                ),
                name="wh_count_counted_qty_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="warehousepurchasereceipt",
            index=models.Index(
                fields=["legal_entity", "state", "receipt_date"], name="wh_purch_rec_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousepurchasereceiptline",
            index=models.Index(fields=["purchase_order_line"], name="wh_purch_rec_po_line_idx"),
        ),
        migrations.AddConstraint(
            model_name="warehousepurchasereceiptline",
            constraint=models.UniqueConstraint(
                fields=("receipt", "sequence"), name="wh_purch_rec_line_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousepurchasereceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="wh_purch_rec_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousepurchasereceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost_snapshot__gt", 0)), name="wh_purch_rec_cost_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturnline",
            constraint=models.UniqueConstraint(
                fields=("supplier_return", "sequence"), name="wh_supplier_return_line_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierreturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="wh_supplier_return_qty_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousesalesissue",
            index=models.Index(
                fields=["legal_entity", "state", "issue_date"], name="wh_sales_issue_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousesalesissueline",
            index=models.Index(fields=["sales_delivery_line"], name="wh_sales_delivery_line_idx"),
        ),
        migrations.AddConstraint(
            model_name="warehousesalesissueline",
            constraint=models.UniqueConstraint(
                fields=("issue", "sequence"), name="wh_sales_issue_line_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousesalesissueline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="wh_sales_issue_qty_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousesubcontractreceipt",
            index=models.Index(
                fields=["legal_entity", "state", "receipt_date"], name="wh_subrec_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warehousesubcontractreceiptline",
            index=models.Index(
                fields=["subcontract_receipt_line"], name="wh_subrec_source_line_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousesubcontractreceiptline",
            constraint=models.UniqueConstraint(
                fields=("receipt", "sequence"), name="wh_subrec_line_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousesubcontractreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="wh_subrec_qty_positive"
            ),
        ),
    ]
