# Generated by Django 5.2.17 on 2026-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0004_alter_stockmovement_movement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("PRODUCTION_MATERIAL_ISSUE", "Issue Bahan Produksi"),
                    ("PRODUCTION_FINISHED_GOODS_RECEIPT", "Terima Hasil Produksi"),
                    ("PURCHASE_RECEIPT", "Penerimaan Pembelian"),
                    ("SUBCONTRACT_RECEIPT", "Penerimaan Maklun"),
                    ("SALES_DELIVERY_ISSUE", "Pengeluaran Penjualan"),
                    ("OPNAME_GAIN", "Stock Opname Gain"),
                    ("OPNAME_LOSS", "Stock Opname Loss"),
                    ("INVENTORY_ADJUSTMENT", "Penyesuaian Stok"),
                    ("INTERNAL_CONSUMPTION", "Pemakaian Internal"),
                    ("SUPPLIER_RETURN", "Retur Supplier"),
                    ("OMNI_PACKING", "Packing Omnichannel"),
                    ("MARKETPLACE_RETURN_RECEIPT", "Penerimaan Retur Marketplace"),
                    ("POS_SALE_ISSUE", "Pengeluaran POS"),
                    ("POS_SALE_REVERSAL", "Pembalikan Pengeluaran POS"),
                    ("POS_RETURN_RECEIPT", "Penerimaan Retur POS"),
                ],
                max_length=48,
            ),
        ),
    ]
