# Generated by Django 5.2.17 on 2026-08-28 04:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_employee"),
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("production", "0006_productionoverheadsnapshot_accounting_treatment_snapshot_and_more"),
        ("purchasing", "0004_phase_4b2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("PRODUCTION_FINISHED_GOODS", "Production finished goods"),
                            ("SUBCONTRACT_RECEIPT", "Subcontract receipt"),
                            ("SUPPLIER_INCOMING", "Supplier incoming"),
                            ("CUSTOMER_RETURN", "Customer return"),
                            ("MARKETPLACE_RETURN", "Marketplace return"),
                            ("RANDOM_INSPECTION", "Random inspection"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_module", models.CharField(max_length=64)),
                ("source_type", models.CharField(max_length=64)),
                ("source_document_id", models.CharField(max_length=64)),
                ("source_key", models.CharField(max_length=255)),
                ("inspection_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("inspector_code_snapshot", models.CharField(blank=True, max_length=64)),
                ("inspector_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=500)),
                ("evidence_metadata", models.JSONField(blank=True, default=dict)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_quality_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspections",
                        to="accounts.employee",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspections",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_quality_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_quality_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspections",
                        to="organizations.warehouse",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_qualityinspection", "Can post quality inspection"),
                    ("reverse_qualityinspection", "Can reverse quality inspection"),
                    ("view_qualitydashboard", "Can view quality dashboard"),
                ],
            },
        ),
        migrations.CreateModel(
            name="QualityInspectionLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_line_id", models.CharField(max_length=64)),
                ("qty_presented", models.DecimalField(decimal_places=6, max_digits=18)),
                ("qty_inspected", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("qty_pass", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("qty_hold", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("qty_reject", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("qty_rework", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                (
                    "qty_legacy_unmapped",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("HOLD", "Hold"),
                            ("REJECT", "Reject"),
                            ("REWORK", "Rework"),
                            ("LEGACY_UNMAPPED", "Legacy unmapped"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_code_snapshot", models.CharField(blank=True, max_length=64)),
                ("reason_text", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="quality.qualityinspection",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "production_handover_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspection_lines",
                        to="production.productionwarehousehandoverline",
                    ),
                ),
                (
                    "subcontract_receipt_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspection_lines",
                        to="purchasing.subcontractreceiptoutputline",
                    ),
                ),
                (
                    "work_order_output",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_inspection_lines",
                        to="purchasing.workorderoutput",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualityInspectionLineReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                ("reversed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="quality.qualityinspectionline",
                    ),
                ),
                (
                    "replacement_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_for_reversal",
                        to="quality.qualityinspectionline",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_line_reversals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QualityReason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "applies_to_result",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("HOLD", "Hold"),
                            ("REJECT", "Reject"),
                            ("REWORK", "Rework"),
                            ("LEGACY_UNMAPPED", "Legacy unmapped"),
                        ],
                        max_length=24,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_reasons",
                        to="organizations.legalentity",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(
                fields=["legal_entity", "state", "inspection_date"],
                name="quality_inspection_list_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qualityinspection",
            index=models.Index(
                fields=["source_module", "source_type", "source_document_id"],
                name="quality_source_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspection",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_key"), name="quality_inspection_source_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityinspectionline",
            index=models.Index(
                fields=["source_line_id", "inspection"], name="quality_line_source_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualityinspectionline",
            index=models.Index(fields=["item", "inspection"], name="quality_line_item_idx"),
        ),
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.UniqueConstraint(
                fields=("inspection", "sequence"), name="quality_line_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_presented__gte", 0)), name="quality_presented_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_inspected__gte", 0)), name="quality_inspected_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_pass__gte", 0)), name="quality_pass_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_hold__gte", 0)), name="quality_hold_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_reject__gte", 0)), name="quality_reject_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_rework__gte", 0)), name="quality_rework_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_legacy_unmapped__gte", 0)),
                name="quality_legacy_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="qualityinspectionlinereversal",
            index=models.Index(fields=["reversed_at"], name="quality_line_rev_time_idx"),
        ),
        migrations.AddIndex(
            model_name="qualityreason",
            index=models.Index(
                fields=["legal_entity", "active", "applies_to_result"],
                name="quality_reason_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityreason",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "code"), name="quality_reason_entity_code_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityreason",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_from__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="quality_reason_effective_period_valid",
            ),
        ),
    ]
