# Generated by Django 5.2.17 on 2026-08-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("production", "0006_productionoverheadsnapshot_accounting_treatment_snapshot_and_more"),
        ("purchasing", "0004_phase_4b2"),
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="qualityinspectionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("qty_inspected__lte", models.F("qty_presented"))),
                name="quality_inspected_lte_presented",
            ),
        ),
    ]
