# Generated by Django 5.2.17 on 2026-08-28 12:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("channels", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("warehouse", "0003_alter_stockmovement_movement_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OmniImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(default="BIGSELLER_ORDER", max_length=60)),
                ("source_filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Preview"),
                            ("READY", "Ready"),
                            ("PARTIAL", "Partial"),
                            ("IMPORTED", "Imported"),
                            ("CONFLICT", "Conflict"),
                        ],
                        default="PREVIEW",
                        max_length=20,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("accepted_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("replay_count", models.PositiveIntegerField(default=0)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("import_omniimportbatch", "Can import Omnichannel orders"),
                    ("commit_omniimportbatch", "Can commit Omnichannel imports"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OmniImportRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                ("source_row_key", models.CharField(max_length=255)),
                ("external_order_number", models.CharField(blank=True, max_length=150)),
                ("external_store_name", models.CharField(blank=True, max_length=255)),
                ("marketplace", models.CharField(blank=True, max_length=80)),
                ("external_sku", models.CharField(blank=True, max_length=150)),
                ("external_sku_normalized", models.CharField(blank=True, max_length=150)),
                ("product", models.CharField(blank=True, max_length=255)),
                ("variation", models.CharField(blank=True, max_length=255)),
                ("variation_normalized", models.CharField(blank=True, max_length=255)),
                (
                    "marketplace_quantity",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "source_subtotal",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("order_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=160)),
                ("raw_status", models.CharField(blank=True, max_length=120)),
                (
                    "normalized_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                            ("REFUNDED", "Refunded"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "conversion_quantity",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("UNMAPPED_STORE", "Unmapped store"),
                            ("UNMAPPED_SKU", "Unmapped SKU"),
                            ("INVALID_QTY", "Invalid quantity"),
                            ("INVALID_ORDER_DATE", "Invalid order date"),
                            ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                            ("MAPPING_INACTIVE", "Mapping inactive"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "row_status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("REJECTED", "Rejected"),
                            ("IMPORTED", "Imported"),
                        ],
                        max_length=12,
                    ),
                ),
                ("exception_code", models.CharField(blank=True, max_length=40)),
                ("exception_message", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rows",
                        to="omnichannel.omniimportbatch",
                    ),
                ),
                (
                    "resolved_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.item",
                    ),
                ),
                (
                    "resolved_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="channels.externalskumap",
                    ),
                ),
                (
                    "resolved_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="channels.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OmniOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marketplace", models.CharField(max_length=80)),
                ("external_store_name", models.CharField(max_length=255)),
                ("store_code_snapshot", models.CharField(blank=True, max_length=50)),
                ("store_name_snapshot", models.CharField(blank=True, max_length=150)),
                ("store_channel_snapshot", models.CharField(blank=True, max_length=50)),
                ("store_mapping_snapshot", models.JSONField(blank=True, default=dict)),
                ("external_order_number", models.CharField(max_length=150)),
                ("source_identity_key", models.CharField(max_length=400)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("raw_status", models.CharField(blank=True, max_length=120)),
                (
                    "normalized_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                            ("REFUNDED", "Refunded"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=160)),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("UNMAPPED_STORE", "Unmapped store"),
                            ("UNMAPPED_SKU", "Unmapped SKU"),
                            ("INVALID_QTY", "Invalid quantity"),
                            ("INVALID_ORDER_DATE", "Invalid order date"),
                            ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                            ("MAPPING_INACTIVE", "Mapping inactive"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        default="READY",
                        max_length=32,
                    ),
                ),
                (
                    "source_sync_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("UNMAPPED_STORE", "Unmapped store"),
                            ("UNMAPPED_SKU", "Unmapped SKU"),
                            ("INVALID_QTY", "Invalid quantity"),
                            ("INVALID_ORDER_DATE", "Invalid order date"),
                            ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                            ("MAPPING_INACTIVE", "Mapping inactive"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        default="READY",
                        max_length=32,
                    ),
                ),
                ("last_source_hash", models.CharField(blank=True, max_length=64)),
                ("source_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_orders",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="omnichannel.omniimportbatch",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_orders",
                        to="channels.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OmniOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_row_key", models.CharField(blank=True, max_length=255)),
                ("external_sku", models.CharField(max_length=150)),
                ("external_sku_normalized", models.CharField(max_length=150)),
                ("product", models.CharField(blank=True, max_length=255)),
                ("variation", models.CharField(blank=True, max_length=255)),
                ("variation_normalized", models.CharField(max_length=255)),
                ("item_code_snapshot", models.CharField(blank=True, max_length=64)),
                ("item_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("mapping_snapshot", models.JSONField(blank=True, default=dict)),
                ("marketplace_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("conversion_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("internal_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "source_subtotal",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("raw_status", models.CharField(blank=True, max_length=120)),
                (
                    "normalized_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("RETURNED", "Returned"),
                            ("REFUNDED", "Refunded"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("UNMAPPED_STORE", "Unmapped store"),
                            ("UNMAPPED_SKU", "Unmapped SKU"),
                            ("INVALID_QTY", "Invalid quantity"),
                            ("INVALID_ORDER_DATE", "Invalid order date"),
                            ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                            ("MAPPING_INACTIVE", "Mapping inactive"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "source_sync_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("UNMAPPED_STORE", "Unmapped store"),
                            ("UNMAPPED_SKU", "Unmapped SKU"),
                            ("INVALID_QTY", "Invalid quantity"),
                            ("INVALID_ORDER_DATE", "Invalid order date"),
                            ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                            ("MAPPING_INACTIVE", "Mapping inactive"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        default="READY",
                        max_length=32,
                    ),
                ),
                ("source_row_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_order_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_order_lines",
                        to="channels.externalskumap",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="omnichannel.omniorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OmniException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40)),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="omnichannel.omniimportbatch",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="omnichannel.omniorder",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exceptions",
                        to="omnichannel.omniorderline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OmniPacking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marketplace", models.CharField(max_length=80)),
                ("packing_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_omni_packings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_packings",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_omni_packings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_packings",
                        to="channels.store",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_packings",
                        to="organizations.warehouse",
                    ),
                ),
            ],
            options={
                "permissions": [("post_omnipacking", "Can post Omnichannel packing")],
            },
        ),
        migrations.CreateModel(
            name="OmniPackingLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("requested_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("packed_quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.item"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packing_lines",
                        to="omnichannel.omniorder",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packing_lines",
                        to="omnichannel.omniorderline",
                    ),
                ),
                (
                    "packing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="omnichannel.omnipacking",
                    ),
                ),
                (
                    "warehouse_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_packing_line",
                        to="warehouse.stockmovement",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="omniimportbatch",
            index=models.Index(
                fields=["legal_entity", "status", "-created_at"], name="omni_import_list_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="omniimportbatch",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_type", "file_hash"),
                name="omni_import_entity_type_hash_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="omniimportrow",
            index=models.Index(fields=["batch", "row_status"], name="omni_import_row_status_idx"),
        ),
        migrations.AddIndex(
            model_name="omniimportrow",
            index=models.Index(
                fields=["external_order_number", "external_sku_normalized"],
                name="omni_import_row_source_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="omniimportrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "source_row_key"), name="omni_import_row_identity_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="omniorder",
            index=models.Index(
                fields=["legal_entity", "order_date", "normalized_status"],
                name="omni_order_operational_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="omniorder",
            index=models.Index(
                fields=["legal_entity", "mapping_status"], name="omni_order_mapping_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="omniorder",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_identity_key"), name="omni_order_source_identity_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="omniorderline",
            index=models.Index(
                fields=["order", "mapping_status"], name="omni_order_line_ready_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="omniorderline",
            index=models.Index(
                fields=["item", "normalized_status"], name="omni_order_line_item_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="omniorderline",
            constraint=models.UniqueConstraint(
                fields=("order", "external_sku_normalized", "variation_normalized"),
                name="omni_order_line_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="omniorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("marketplace_quantity__gt", 0)),
                name="omni_order_line_marketplace_qty_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="omniorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("conversion_quantity__gt", 0)),
                name="omni_order_line_conversion_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="omniorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("internal_quantity__gt", 0)),
                name="omni_order_line_internal_qty_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="omniexception",
            index=models.Index(
                fields=["legal_entity", "state", "code"], name="omni_exception_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="omnipacking",
            index=models.Index(
                fields=["legal_entity", "state", "packing_date"], name="omni_packing_list_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="omnipackingline",
            index=models.Index(fields=["order_line"], name="omni_packing_order_line_idx"),
        ),
        migrations.AddConstraint(
            model_name="omnipackingline",
            constraint=models.UniqueConstraint(
                fields=("packing", "sequence"), name="omni_packing_line_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="omnipackingline",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_quantity__gt", 0)),
                name="omni_packing_req_qty_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="omnipackingline",
            constraint=models.CheckConstraint(
                condition=models.Q(("packed_quantity__gt", 0)), name="omni_packing_qty_positive"
            ),
        ),
    ]
