# Generated by Django 5.2.17 on 2026-08-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("channels", "0001_initial"),
        ("omnichannel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="omniorderline",
            name="omni_order_line_conversion_positive",
        ),
        migrations.RemoveConstraint(
            model_name="omniorderline",
            name="omni_order_line_internal_qty_positive",
        ),
        migrations.AlterField(
            model_name="omniorderline",
            name="conversion_quantity",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="omniorderline",
            name="internal_quantity",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AddConstraint(
            model_name="omniorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("conversion_quantity__isnull", True),
                    ("conversion_quantity__gt", 0),
                    _connector="OR",
                ),
                name="omni_order_line_conversion_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="omniorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("internal_quantity__isnull", True),
                    ("internal_quantity__gt", 0),
                    _connector="OR",
                ),
                name="omni_order_line_internal_qty_positive",
            ),
        ),
    ]
