# Generated by Django 5.2.17 on 2026-08-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omnichannel", "0002_remove_omniorderline_omni_order_line_conversion_positive_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="omniimportrow",
            name="mapping_status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("UNMAPPED_STORE", "Unmapped store"),
                    ("UNMAPPED_SKU", "Unmapped SKU"),
                    ("INVALID_QTY", "Invalid quantity"),
                    ("INVALID_ORDER_DATE", "Invalid order date"),
                    ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                    ("MAPPING_INACTIVE", "Mapping inactive"),
                    ("DUPLICATE_SOURCE", "Duplicate source row"),
                    ("SOURCE_CHANGED", "Source changed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="omniorder",
            name="mapping_status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("UNMAPPED_STORE", "Unmapped store"),
                    ("UNMAPPED_SKU", "Unmapped SKU"),
                    ("INVALID_QTY", "Invalid quantity"),
                    ("INVALID_ORDER_DATE", "Invalid order date"),
                    ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                    ("MAPPING_INACTIVE", "Mapping inactive"),
                    ("DUPLICATE_SOURCE", "Duplicate source row"),
                    ("SOURCE_CHANGED", "Source changed"),
                ],
                default="READY",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="omniorder",
            name="source_sync_status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("UNMAPPED_STORE", "Unmapped store"),
                    ("UNMAPPED_SKU", "Unmapped SKU"),
                    ("INVALID_QTY", "Invalid quantity"),
                    ("INVALID_ORDER_DATE", "Invalid order date"),
                    ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                    ("MAPPING_INACTIVE", "Mapping inactive"),
                    ("DUPLICATE_SOURCE", "Duplicate source row"),
                    ("SOURCE_CHANGED", "Source changed"),
                ],
                default="READY",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="omniorderline",
            name="mapping_status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("UNMAPPED_STORE", "Unmapped store"),
                    ("UNMAPPED_SKU", "Unmapped SKU"),
                    ("INVALID_QTY", "Invalid quantity"),
                    ("INVALID_ORDER_DATE", "Invalid order date"),
                    ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                    ("MAPPING_INACTIVE", "Mapping inactive"),
                    ("DUPLICATE_SOURCE", "Duplicate source row"),
                    ("SOURCE_CHANGED", "Source changed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="omniorderline",
            name="source_sync_status",
            field=models.CharField(
                choices=[
                    ("READY", "Ready"),
                    ("UNMAPPED_STORE", "Unmapped store"),
                    ("UNMAPPED_SKU", "Unmapped SKU"),
                    ("INVALID_QTY", "Invalid quantity"),
                    ("INVALID_ORDER_DATE", "Invalid order date"),
                    ("INVALID_COMPLETION_DATE", "Invalid completion date"),
                    ("MAPPING_INACTIVE", "Mapping inactive"),
                    ("DUPLICATE_SOURCE", "Duplicate source row"),
                    ("SOURCE_CHANGED", "Source changed"),
                ],
                default="READY",
                max_length=32,
            ),
        ),
    ]
