# Generated by Django 5.2.17 on 2026-08-31 15:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("channels", "0001_initial"),
        ("omnichannel", "0003_alter_omniimportrow_mapping_status_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("quality", "0002_qualityinspectionline_quality_inspected_lte_presented"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OmniReturnImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(default="BIGSELLER_RETURN", max_length=60)),
                ("source_filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="IMPORTED", max_length=24)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_return_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_return_batches",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("import_omnireturnsource", "Can import marketplace returns"),
                    ("manage_omnireturnsource", "Can manage marketplace returns"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OmniReturnSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marketplace", models.CharField(blank=True, max_length=80)),
                ("external_store_name", models.CharField(blank=True, max_length=255)),
                ("package_number", models.CharField(blank=True, max_length=180)),
                ("external_order_number", models.CharField(blank=True, max_length=150)),
                ("external_return_id", models.CharField(blank=True, max_length=180)),
                ("external_sku", models.CharField(blank=True, max_length=150)),
                ("warehouse_sku", models.CharField(blank=True, max_length=150)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "stock_addition_quantity",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "inspected_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "quality_accepted_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "warehouse_returned_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "refunded_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "refund_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=12)),
                ("order_status", models.CharField(blank=True, max_length=120)),
                ("shipping_status", models.CharField(blank=True, max_length=120)),
                ("aftersales_status", models.CharField(blank=True, max_length=120)),
                ("return_status", models.CharField(blank=True, max_length=120)),
                ("stock_addition_status", models.CharField(blank=True, max_length=120)),
                ("return_type", models.CharField(blank=True, max_length=120)),
                ("return_reason", models.CharField(blank=True, max_length=255)),
                ("order_date", models.DateTimeField(blank=True, null=True)),
                ("return_requested_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("stock_added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "linkage_status",
                    models.CharField(
                        choices=[
                            ("MATCHED", "Matched"),
                            ("UNMATCHED_ORDER", "Unmatched order"),
                            ("UNMATCHED_SKU", "Unmatched SKU"),
                            ("AMBIGUOUS_ORDER_LINE", "Ambiguous order line"),
                            ("BLOCKED_MAPPING", "Blocked mapping"),
                        ],
                        default="UNMATCHED_ORDER",
                        max_length=32,
                    ),
                ),
                ("linkage_message", models.TextField(blank=True)),
                ("source_row_key", models.CharField(max_length=255)),
                ("source_identity_key", models.CharField(max_length=500)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="omnichannel.omnireturnimportbatch",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "original_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_sources",
                        to="omnichannel.omniorder",
                    ),
                ),
                (
                    "original_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_sources",
                        to="omnichannel.omniorderline",
                    ),
                ),
                (
                    "quality_inspection_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_return_sources",
                        to="quality.qualityinspectionline",
                    ),
                ),
                (
                    "resolved_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_return_sources",
                        to="catalog.item",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_returns",
                        to="channels.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OmniRevenueEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marketplace", models.CharField(max_length=80)),
                ("external_order_number", models.CharField(max_length=150)),
                ("completion_date", models.DateField()),
                ("currency", models.CharField(default="IDR", max_length=12)),
                (
                    "gross_eligible_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("source_components", models.JSONField(blank=True, default=dict)),
                ("source_lineage", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ELIGIBLE", "Eligible"),
                            ("BLOCKED_AMOUNT", "Blocked amount"),
                            ("BLOCKED_MAPPING", "Blocked mapping"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="ELIGIBLE",
                        max_length=24,
                    ),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("COMPLETED_NOT_SETTLED", "Completed not settled"),
                            ("SETTLEMENT_MATCH", "Settlement match"),
                            ("SETTLEMENT_PARTIAL", "Settlement partial"),
                            ("SETTLEMENT_UNMATCHED", "Settlement unmatched"),
                            ("SETTLEMENT_OVER", "Settlement over"),
                            ("RETURN_PENDING", "Return pending"),
                            ("REFUND_PENDING", "Refund pending"),
                            ("ADJUSTMENT_PENDING", "Adjustment pending"),
                            ("PAYOUT_PENDING", "Payout pending"),
                            ("PAYOUT_MATCH", "Payout match"),
                            ("BLOCKED_MAPPING", "Blocked mapping"),
                            ("UNMATCHED_RETURN", "Unmatched return"),
                            ("AMBIGUOUS_ORDER_LINE", "Ambiguous order line"),
                            ("UNMATCHED_PAYOUT", "Unmatched payout"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        default="BLOCKED_MAPPING",
                        max_length=24,
                    ),
                ),
                ("event_key", models.CharField(max_length=400, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_omni_revenue_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_revenue_events",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revenue_events",
                        to="omnichannel.omniorder",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="omnichannel.omnirevenueevent",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_revenue_events",
                        to="channels.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OmniSettlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_store_name", models.CharField(blank=True, max_length=255)),
                ("marketplace", models.CharField(blank=True, max_length=80)),
                ("settlement_reference", models.CharField(blank=True, max_length=180)),
                ("external_order_number", models.CharField(blank=True, max_length=150)),
                ("settlement_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=12)),
                (
                    "gross_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "settled_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "fee_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "refund_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "net_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("fee_components", models.JSONField(blank=True, default=dict)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("source_row_key", models.CharField(max_length=255)),
                ("source_identity_key", models.CharField(max_length=500)),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("COMPLETED_NOT_SETTLED", "Completed not settled"),
                            ("SETTLEMENT_MATCH", "Settlement match"),
                            ("SETTLEMENT_PARTIAL", "Settlement partial"),
                            ("SETTLEMENT_UNMATCHED", "Settlement unmatched"),
                            ("SETTLEMENT_OVER", "Settlement over"),
                            ("RETURN_PENDING", "Return pending"),
                            ("REFUND_PENDING", "Refund pending"),
                            ("ADJUSTMENT_PENDING", "Adjustment pending"),
                            ("PAYOUT_PENDING", "Payout pending"),
                            ("PAYOUT_MATCH", "Payout match"),
                            ("BLOCKED_MAPPING", "Blocked mapping"),
                            ("UNMATCHED_RETURN", "Unmatched return"),
                            ("AMBIGUOUS_ORDER_LINE", "Ambiguous order line"),
                            ("UNMATCHED_PAYOUT", "Unmatched payout"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        default="SETTLEMENT_UNMATCHED",
                        max_length=32,
                    ),
                ),
                ("reconciliation_message", models.TextField(blank=True)),
                (
                    "conflict_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="omnichannel.omnisettlement",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="organizations.legalentity"
                    ),
                ),
                (
                    "matched_revenue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="omnichannel.omnirevenueevent",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_settlements",
                        to="channels.store",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OmniSettlementFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fee_type", models.CharField(max_length=80)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("source_key", models.CharField(max_length=500, unique=True)),
                ("source_row_key", models.CharField(max_length=255)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("mapping_status", models.CharField(default="BLOCKED_MAPPING", max_length=24)),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees",
                        to="omnichannel.omnisettlement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OmniSettlementImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(default="BIGSELLER_SETTLEMENT", max_length=60)),
                ("source_filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="IMPORTED", max_length=24)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_settlement_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_settlement_batches",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "permissions": [("import_omnisettlement", "Can import marketplace settlements")],
            },
        ),
        migrations.AddField(
            model_name="omnisettlement",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlements",
                to="omnichannel.omnisettlementimportbatch",
            ),
        ),
        migrations.CreateModel(
            name="OmniAdjustmentSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marketplace", models.CharField(blank=True, max_length=80)),
                ("external_order_number", models.CharField(blank=True, max_length=150)),
                ("adjustment_type", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("transaction_date", models.DateField(blank=True, null=True)),
                ("source_row_key", models.CharField(max_length=255)),
                ("source_identity_key", models.CharField(max_length=500)),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("COMPLETED_NOT_SETTLED", "Completed not settled"),
                            ("SETTLEMENT_MATCH", "Settlement match"),
                            ("SETTLEMENT_PARTIAL", "Settlement partial"),
                            ("SETTLEMENT_UNMATCHED", "Settlement unmatched"),
                            ("SETTLEMENT_OVER", "Settlement over"),
                            ("RETURN_PENDING", "Return pending"),
                            ("REFUND_PENDING", "Refund pending"),
                            ("ADJUSTMENT_PENDING", "Adjustment pending"),
                            ("PAYOUT_PENDING", "Payout pending"),
                            ("PAYOUT_MATCH", "Payout match"),
                            ("BLOCKED_MAPPING", "Blocked mapping"),
                            ("UNMATCHED_RETURN", "Unmatched return"),
                            ("AMBIGUOUS_ORDER_LINE", "Ambiguous order line"),
                            ("UNMATCHED_PAYOUT", "Unmatched payout"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        default="ADJUSTMENT_PENDING",
                        max_length=32,
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_adjustments",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_adjustments",
                        to="channels.store",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="omnichannel.omnisettlement",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_sources",
                        to="omnichannel.omnisettlementimportbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OmniPayoutSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("marketplace", models.CharField(blank=True, max_length=80)),
                ("payout_reference", models.CharField(max_length=180)),
                ("payout_date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=12)),
                ("settlement_references", models.JSONField(blank=True, default=list)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("source_row_key", models.CharField(blank=True, max_length=255)),
                ("source_identity_key", models.CharField(max_length=500)),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("COMPLETED_NOT_SETTLED", "Completed not settled"),
                            ("SETTLEMENT_MATCH", "Settlement match"),
                            ("SETTLEMENT_PARTIAL", "Settlement partial"),
                            ("SETTLEMENT_UNMATCHED", "Settlement unmatched"),
                            ("SETTLEMENT_OVER", "Settlement over"),
                            ("RETURN_PENDING", "Return pending"),
                            ("REFUND_PENDING", "Refund pending"),
                            ("ADJUSTMENT_PENDING", "Adjustment pending"),
                            ("PAYOUT_PENDING", "Payout pending"),
                            ("PAYOUT_MATCH", "Payout match"),
                            ("BLOCKED_MAPPING", "Blocked mapping"),
                            ("UNMATCHED_RETURN", "Unmatched return"),
                            ("AMBIGUOUS_ORDER_LINE", "Ambiguous order line"),
                            ("UNMATCHED_PAYOUT", "Unmatched payout"),
                            ("SOURCE_CHANGED", "Source changed"),
                        ],
                        default="UNMATCHED_PAYOUT",
                        max_length=32,
                    ),
                ),
                ("reconciliation_message", models.TextField(blank=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_omni_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_payouts",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="omni_payouts",
                        to="channels.store",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("manage_omnipayoutsource", "Can manage marketplace payout handoff")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legal_entity", "source_identity_key"),
                        name="omni_payout_identity_uq",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="omnireturnimportbatch",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_type", "file_hash"),
                name="omni_return_batch_hash_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="omnireturnsource",
            index=models.Index(
                fields=["legal_entity", "arrived_at"], name="omni_return_arrival_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="omnireturnsource",
            index=models.Index(
                fields=["legal_entity", "linkage_status"], name="omni_return_link_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="omnireturnsource",
            index=models.Index(
                fields=["original_order", "external_sku"], name="omni_return_order_sku_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="omnireturnsource",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_identity_key"),
                name="omni_return_source_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="omnireturnsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="omni_return_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="omnireturnsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("inspected_quantity__gte", 0),
                    ("quality_accepted_quantity__gte", 0),
                    ("warehouse_returned_quantity__gte", 0),
                    ("refunded_quantity__gte", 0),
                ),
                name="omni_return_followup_qty_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="omnirevenueevent",
            index=models.Index(
                fields=["legal_entity", "completion_date", "state"],
                name="omni_revenue_date_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="omnirevenueevent",
            index=models.Index(
                fields=["legal_entity", "store", "marketplace"], name="omni_revenue_store_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="omnirevenueevent",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "order"), name="omni_revenue_entity_order_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="omnisettlementimportbatch",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_type", "file_hash"),
                name="omni_settle_batch_hash_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="omnisettlement",
            index=models.Index(
                fields=["legal_entity", "settlement_date"], name="omni_settle_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="omnisettlement",
            index=models.Index(fields=["matched_revenue"], name="omni_settle_revenue_idx"),
        ),
        migrations.AddConstraint(
            model_name="omnisettlement",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_identity_key"),
                name="omni_settle_source_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="omniadjustmentsource",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "source_identity_key"), name="omni_adjustment_identity_uq"
            ),
        ),
    ]
