# Generated by Django 5.2.17 on 2026-08-31 17:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("channels", "0001_initial"),
        ("omnichannel", "0004_omnireturnimportbatch_omnireturnsource_and_more"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("quality", "0002_qualityinspectionline_quality_inspected_lte_presented"),
        ("warehouse", "0005_alter_stockmovement_movement_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosCashSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opened_at", models.DateTimeField()),
                (
                    "opening_cash_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_cash_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "counted_cash_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "variance_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_pos_cash_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_cash_sessions",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_pos_cash_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_cash_sessions",
                        to="channels.store",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("open_poscashsession", "Can open POS cash session"),
                    ("close_poscashsession", "Can close POS cash session"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PosSale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=80)),
                ("sales_channel", models.CharField(default="POS", max_length=50)),
                ("transaction_at", models.DateTimeField()),
                ("transaction_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED", "Posted"),
                            ("REVERSED", "Reversed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("currency", models.CharField(default="IDR", max_length=12)),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "grand_total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("idempotency_key", models.CharField(blank=True, max_length=255)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_pos_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pos_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sales",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_pos_sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sales",
                        to="channels.store",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sales",
                        to="organizations.warehouse",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("post_possale", "Can post POS sale"),
                    ("reverse_possale", "Can reverse POS sale"),
                    ("view_storeanalytics", "Can view Store analytics"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PosReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=80)),
                ("return_at", models.DateTimeField()),
                ("return_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[("RECORDED", "Recorded"), ("CANCELLED", "Cancelled")],
                        default="RECORDED",
                        max_length=12,
                    ),
                ),
                ("currency", models.CharField(default="IDR", max_length=12)),
                (
                    "refund_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_refunds",
                        to="omnichannel.poscashsession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pos_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_returns",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_returns",
                        to="channels.store",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_returns",
                        to="organizations.warehouse",
                    ),
                ),
                (
                    "original_sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="omnichannel.possale",
                    ),
                ),
            ],
            options={
                "permissions": [("manage_posreturn", "Can manage POS return")],
            },
        ),
        migrations.CreateModel(
            name="PosSaleLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_code_snapshot", models.CharField(max_length=64)),
                ("item_name_snapshot", models.CharField(max_length=255)),
                ("uom_code_snapshot", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("unit_price_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("line_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "warehouse_unit_cost",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                (
                    "cogs_amount",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                ("valuation_status", models.CharField(default="PENDING_VALUATION", max_length=24)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sale_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="omnichannel.possale",
                    ),
                ),
                (
                    "warehouse_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_sale_line",
                        to="warehouse.stockmovement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PosReturnLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "inspected_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "quality_accepted_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "warehouse_returned_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "refunded_quantity",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "refund_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
                ),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_return_lines",
                        to="catalog.item",
                    ),
                ),
                (
                    "pos_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="omnichannel.posreturn",
                    ),
                ),
                (
                    "quality_inspection_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_return_lines",
                        to="quality.qualityinspectionline",
                    ),
                ),
                (
                    "original_sale_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="omnichannel.possaleline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PosFinanceSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_code", models.CharField(max_length=64)),
                ("transaction_date", models.DateField()),
                (
                    "amount",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
                ),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("mapping_status", models.CharField(default="BLOCKED_MAPPING", max_length=24)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REVERSED", "Reversed"),
                            ("BLOCKED_MAPPING", "Blocked mapping"),
                            ("PENDING_VALUATION", "Pending valuation"),
                        ],
                        default="ACTIVE",
                        max_length=24,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_sources",
                        to="omnichannel.poscashsession",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_finance_sources",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="omnichannel.posfinancesource",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_finance_sources",
                        to="channels.store",
                    ),
                ),
                (
                    "pos_return",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_sources",
                        to="omnichannel.posreturn",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_sources",
                        to="omnichannel.possale",
                    ),
                ),
                (
                    "sale_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_sources",
                        to="omnichannel.possaleline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PosSaleReversal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reversal_date", models.DateField()),
                ("reason", models.TextField()),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("idempotency_key", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pos_sale_reversals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal",
                        to="omnichannel.possale",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PosTender",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("QRIS", "QRIS"),
                            ("OTHER", "Other configured method"),
                        ],
                        max_length=20,
                    ),
                ),
                ("method_reference", models.CharField(blank=True, max_length=160)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="IDR", max_length=12)),
                ("transaction_at", models.DateTimeField()),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("mapping_status", models.CharField(default="BLOCKED_MAPPING", max_length=24)),
                (
                    "cash_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenders",
                        to="omnichannel.poscashsession",
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tender",
                        to="omnichannel.possale",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="poscashsession",
            index=models.Index(
                fields=["legal_entity", "store", "state"], name="pos_cash_session_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="poscashsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "OPEN")),
                fields=("legal_entity", "store"),
                name="pos_cash_one_open_store_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="poscashsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("opening_cash_amount__gte", 0)),
                name="pos_cash_opening_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="possale",
            index=models.Index(
                fields=["legal_entity", "store", "transaction_date", "state"],
                name="pos_sale_analytics_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="possale",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"), name="pos_sale_document_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="possale",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal_amount__gte", 0),
                    ("discount_amount__gte", 0),
                    ("grand_total_amount__gte", 0),
                ),
                name="pos_sale_amounts_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="posreturn",
            constraint=models.UniqueConstraint(
                fields=("legal_entity", "document_number"), name="pos_return_document_number_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="posreturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("refunded_amount__gte", 0)),
                name="pos_return_refunded_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="possaleline",
            constraint=models.UniqueConstraint(
                fields=("sale", "sequence"), name="pos_sale_line_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="possaleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="pos_sale_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="possaleline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price_amount__gte", 0)),
                name="pos_sale_line_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="posreturnline",
            constraint=models.UniqueConstraint(
                fields=("pos_return", "sequence"), name="pos_return_line_sequence_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="posreturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="pos_return_line_qty_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="posreturnline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("inspected_quantity__gte", 0),
                    ("quality_accepted_quantity__gte", 0),
                    ("warehouse_returned_quantity__gte", 0),
                    ("refunded_quantity__gte", 0),
                ),
                name="pos_return_line_followup_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="posfinancesource",
            index=models.Index(
                fields=["legal_entity", "store", "transaction_date", "event_code"],
                name="pos_finance_analytics_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="postender",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="pos_tender_amount_nonnegative"
            ),
        ),
    ]
