# Generated by Django 5.2.17 on 2026-08-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("omnichannel", "0005_poscashsession_possale_posreturn_possaleline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poscashsession",
            name="close_idempotency_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
