# Generated by Django 5.2.17 on 2026-08-26 01:55

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("registration_status", models.CharField(default="UNKNOWN", max_length=60)),
                ("tax_classification_key", models.CharField(blank=True, max_length=80)),
                ("registration_reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_registrations",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_registrations",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ("registration_status", "-effective_from"),
                "indexes": [
                    models.Index(fields=["legal_entity", "is_active"], name="tax_reg_entity_idx"),
                    models.Index(
                        fields=["business_partner", "is_active"], name="tax_reg_partner_idx"
                    ),
                    models.Index(
                        fields=["tax_classification_key", "is_active"],
                        name="tax_reg_classification_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("business_partner__isnull", True), ("legal_entity__isnull", False)
                            ),
                            models.Q(
                                ("business_partner__isnull", False), ("legal_entity__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="tax_registration_one_subject",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("business_partner__isnull", True)),
                        fields=("legal_entity", "effective_from"),
                        name="tax_registration_entity_start_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("legal_entity__isnull", True)),
                        fields=("business_partner", "effective_from"),
                        name="tax_registration_partner_start_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="tax_taxregistration_effective_period_valid",
                    ),
                ],
            },
        ),
    ]
