# Generated by Django 5.2.17 on 2026-08-25 14:19

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="catalog.itemcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "item categories",
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="UOM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "dimension",
                    models.CharField(
                        help_text="Stable dimension key such as COUNT, LENGTH, WEIGHT, or VOLUME.",
                        max_length=40,
                    ),
                ),
                ("decimal_places", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "unit of measure",
                "verbose_name_plural": "units of measure",
                "ordering": ("code",),
                "indexes": [
                    models.Index(fields=["dimension", "is_active"], name="cat_uom_dim_active_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("code"),
                        name="catalog_uom_code_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="catalog_uom_effective_period_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "item_kind",
                    models.CharField(
                        choices=[
                            ("PRODUCT", "Product"),
                            ("MATERIAL", "Material"),
                            ("SERVICE", "Service"),
                            ("PACKAGING", "Packaging"),
                            ("OTHER", "Other"),
                        ],
                        default="PRODUCT",
                        max_length=20,
                    ),
                ),
                ("variant_attributes", models.JSONField(blank=True, default=dict)),
                ("sales_eligible", models.BooleanField(default=False)),
                ("purchase_eligible", models.BooleanField(default=False)),
                ("production_eligible", models.BooleanField(default=False)),
                ("inventory_eligible", models.BooleanField(default=False)),
                ("tax_classification", models.CharField(blank=True, max_length=64)),
                ("valuation_policy", models.CharField(blank=True, max_length=64)),
                ("minimum_stock", models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ("lead_time_days", models.PositiveIntegerField(default=0)),
                ("reference_cost", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "reference_selling_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="organizations.legalentity",
                    ),
                ),
                (
                    "parent_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional parent product. Every variant remains a canonical Item.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.item",
                    ),
                ),
                (
                    "preferred_vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferred_items",
                        to="partners.businesspartner",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_items",
                        to="catalog.itemcategory",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcategory_items",
                        to="catalog.itemcategory",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="catalog.uom",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.AddIndex(
            model_name="itemcategory",
            index=models.Index(fields=["parent", "is_active"], name="cat_category_parent_idx"),
        ),
        migrations.AddConstraint(
            model_name="itemcategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="catalog_category_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="catalog_category_effective_period_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["legal_entity", "is_active"], name="catalog_item_entity_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["item_kind", "is_active"], name="catalog_item_kind_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["parent_item", "is_active"], name="catalog_item_parent_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"), name="catalog_item_code_ci_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_stock__gte", 0)),
                name="catalog_item_minimum_stock_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference_cost__gte", 0)),
                name="catalog_item_reference_cost_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference_selling_price__gte", 0)),
                name="catalog_item_selling_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="catalog_item_effective_period_valid",
            ),
        ),
    ]
