# Generated by Django 5.2.17 on 2026-08-25 15:17

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("organizations", "0002_businessunit_costcenter_department_warehouse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=150)),
                (
                    "channel",
                    models.CharField(
                        help_text="Stable platform/channel key such as SHOPEE, TIKTOK, POS, or B2B.",
                        max_length=50,
                    ),
                ),
                ("external_account_id", models.CharField(blank=True, max_length=120)),
                ("external_aliases", models.JSONField(blank=True, default=list)),
                ("finance_dimension", models.CharField(blank=True, max_length=80)),
                ("revenue_mapping_key", models.CharField(blank=True, max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stores",
                        to="organizations.businessunit",
                    ),
                ),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stores",
                        to="organizations.legalentity",
                    ),
                ),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="ExternalSKUMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("external_sku", models.CharField(max_length=150)),
                ("external_sku_normalized", models.CharField(editable=False, max_length=150)),
                ("external_product_name", models.CharField(blank=True, max_length=255)),
                ("external_variation", models.CharField(blank=True, max_length=255)),
                (
                    "external_variation_normalized",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "conversion_quantity",
                    models.DecimalField(decimal_places=6, default=1, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_sku_mappings",
                        to="catalog.item",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sku_mappings",
                        to="channels.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "external SKU mapping",
                "ordering": (
                    "store__code",
                    "external_sku",
                    "external_variation",
                    "-effective_from",
                ),
            },
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["legal_entity", "channel", "is_active"], name="channels_store_scope_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"), name="channels_store_code_ci_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_account_id", ""), _negated=True),
                fields=("legal_entity", "channel", "external_account_id"),
                name="channels_store_external_account_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="store",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="channels_store_effective_period_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="externalskumap",
            index=models.Index(
                fields=[
                    "store",
                    "external_sku_normalized",
                    "external_variation_normalized",
                    "is_active",
                ],
                name="channels_skumap_lookup_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalskumap",
            constraint=models.UniqueConstraint(
                fields=(
                    "store",
                    "external_sku_normalized",
                    "external_variation_normalized",
                    "effective_from",
                ),
                name="channels_skumap_scope_start_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalskumap",
            constraint=models.CheckConstraint(
                condition=models.Q(("conversion_quantity__gt", 0)),
                name="channels_skumap_conversion_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalskumap",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="channels_skumap_effective_period_valid",
            ),
        ),
    ]
