# Generated by Django 5.2.17 on 2026-08-25 14:19

import uuid

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("document_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production"),
                            ("WAREHOUSE", "Warehouse"),
                            ("OFFICE", "Office"),
                            ("SALES_MARKETING", "Sales & Marketing"),
                            ("GENERAL", "General"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=32,
                    ),
                ),
                ("is_production_overhead_eligible", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("effective_from", models.DateField(default=django.utils.timezone.localdate)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("province", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
        migrations.AddField(
            model_name="legalentity",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="country_code",
            field=models.CharField(default="ID", max_length=2),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="effective_from",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="effective_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="is_pkp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="nitku",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="npwp",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="province",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="reporting_currency",
            field=models.CharField(default="IDR", max_length=3),
        ),
        migrations.AddField(
            model_name="legalentity",
            name="timezone",
            field=models.CharField(default="Asia/Jakarta", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="legalentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="organizations_legalentity_effective_period_valid",
            ),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="legal_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_units",
                to="organizations.legalentity",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_centers",
                to="organizations.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="legal_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_centers",
                to="organizations.legalentity",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="organizations.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="legal_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="organizations.legalentity",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="organizations.department",
            ),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cost_centers",
                to="organizations.department",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouses",
                to="organizations.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="legal_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouses",
                to="organizations.legalentity",
            ),
        ),
        migrations.AddIndex(
            model_name="businessunit",
            index=models.Index(
                fields=["legal_entity", "is_active"], name="org_bu_entity_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="businessunit",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="organizations_businessunit_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="businessunit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="organizations_businessunit_effective_period_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["legal_entity", "is_active"], name="org_dept_entity_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="organizations_department_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="organizations_department_effective_period_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="costcenter",
            index=models.Index(
                fields=["legal_entity", "is_active"], name="org_cc_entity_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costcenter",
            index=models.Index(
                fields=["is_production_overhead_eligible", "is_active"],
                name="org_cc_prod_eligible_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="organizations_costcenter_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="organizations_costcenter_effective_period_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["legal_entity", "is_active"], name="org_wh_entity_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                name="organizations_warehouse_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("legal_entity",),
                name="organizations_one_default_warehouse_per_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_to__isnull", True),
                    ("effective_to__gte", models.F("effective_from")),
                    _connector="OR",
                ),
                name="organizations_warehouse_effective_period_valid",
            ),
        ),
    ]
